/**
 * The UGC creator document — the three-tab brief format (Sep 2026).
 *
 * Kia's decision: every UGC brief ships as ONE Google Doc with THREE tabs
 * (Creator Brief · Script · Strategy), in the exact style of the reference
 * document `docxTemplate/EXAMPLE-UGC-brief.docx` (a Google Docs export):
 * same fonts, sizes, colors, borders, shading, margins, and — above all —
 * the same trimmed level of information. Nothing more, nothing less.
 *
 * This file is the RENDERER-AGNOSTIC model: a document is tabs of blocks.
 * Two renderers consume it —
 *   · `ugcDocx.ts`       → a real .docx (download), cloned from the example's
 *                          own XML so the formatting is byte-for-byte the same
 *   · `../api/googleDocs.ts` → a Google Doc with real tabs via the Docs API
 * and `buildUgcDocument()` (below) maps a finished UgcBriefV2 onto it.
 *
 * STYLE SPEC (measured from the example; every renderer reproduces it):
 *   Page          A4 portrait (595.3 × 841.9 pt); margins top/bottom 3 cm
 *                 (85.05 pt), left/right 2 cm (56.7 pt).
 *   Base font     Arial 11 pt, black; body line spacing 1.15.
 *   title         Tab title paragraph — 26 pt, regular, black, spacing 0.
 *   heading       Heading 1 — bold, 16 pt, color #203f66, 8 pt before + after.
 *   paragraph     Normal — 11 pt, regular.
 *   readThroughLabel  bold 12 pt; 16.5 pt before, 7.5 pt after; single spacing.
 *   readThrough   10 pt on a #f8f9fb shaded run; line spacing 1.5;
 *                 7.5 pt before, 19.5 pt after; right indent 10.5 pt.
 *   bullets       ● list, 9 pt; left indent 36 pt, hanging 18 pt.
 *   kvTable       2 columns × 241 pt; 1 pt black borders (all); label cells
 *                 shaded #edf2fa, bold 9 pt; value cells 9 pt; single spacing.
 *   scriptTable   4 columns × 120.5 pt; header row shaded #203f66, bold white
 *                 8 pt; LINE/SECTION and SHOT/ACTION cells bold 8 pt; SCRIPT
 *                 LINE and ON-SCREEN TEXT cells 8 pt.
 *   strategyTable 3 columns × 160.67 pt; header row shaded #203f66, bold white
 *                 9 pt; SECTION column merged vertically per group, bold 9 pt;
 *                 FIELD column bold 9 pt; DIRECTION column 9 pt; every body row
 *                 at least 19 pt tall.
 */

import type { UgcBriefV2, V2Row } from './v2Types';
import { taskAdType } from './v2Types';

// ─── The model ──────────────────────────────────────────────────────────────

export interface UgcDocument {
  /** The file / Google Doc name (= the task name). */
  title: string;
  tabs: [UgcDocTab, UgcDocTab, UgcDocTab];
}

export interface UgcDocTab {
  /** Tab name in Google Docs; also rendered as the tab's title paragraph. */
  title: string;
  blocks: UgcDocBlock[];
}

export type UgcDocBlock =
  | { kind: 'title'; text: string }
  | { kind: 'heading'; text: string }
  | { kind: 'paragraph'; text: string }
  | { kind: 'readThroughLabel'; text: string }
  | { kind: 'readThrough'; text: string }
  | { kind: 'bullets'; items: string[] }
  | { kind: 'kvTable'; rows: UgcKvRow[] }
  | { kind: 'scriptTable'; header: [string, string, string, string]; rows: UgcScriptRow[] }
  | { kind: 'strategyTable'; header: [string, string, string]; groups: UgcStrategyGroup[] };

export interface UgcKvRow {
  label: string;
  /** Paragraphs of the value cell. An empty string is a blank paragraph
   *  (the example separates the creator-note paragraphs with blank lines). */
  value: string[];
}

export interface UgcScriptRow {
  /** LINE / SECTION — e.g. "HOOK 1", "HOOK 4 — SALE FIRST", "BODY 5 — PRODUCT REVEAL", "OFFER", "CTA". */
  label: string;
  shot: string;
  line: string;
  /** ON-SCREEN TEXT — empty for most body lines. */
  overlay: string;
}

export interface UgcStrategyGroup {
  /** SECTION cell, merged down the group: "Strategy" | "Offer" | "Production" | "Editing" | "Reference". */
  section: string;
  fields: Array<{ field: string; direction: string }>;
}

// ─── The brief's document fields (generated by the writer, edited in-app) ───

/** The fields of the three-tab document that the brief object must carry
 *  beyond hooks / CTAs / prose / storyboard. Generated by the UGC writer in
 *  the same call as the script (calibrated on the example document), shown
 *  and regenerable in the editor, rendered by `buildUgcDocument`. */
export interface UgcCreatorDoc {
  /** Creator Brief tab → BRIEF INFO. */
  briefInfo: {
    /** e.g. "EasyStretch™" */
    collection: string;
    /** The exact socks / patterns the creator receives, e.g. "2 EasyStretch Socks — Legacy and Snoopy pattern". */
    socks: string;
    /** e.g. "9:16 creator-filmed UGC demonstration + testimonial" */
    format: string;
    /** Who the creator must be, one line. */
    creatorRequirement: string;
    /** The friendly note to the creator — 3-4 short paragraphs. */
    creatorNote: string[];
  };
  /** Script tab → CREATOR NOTE (one short paragraph) + BEFORE YOU SUBMIT (bullets). */
  scriptNote: string;
  beforeYouSubmit: string[];
  /** Strategy tab. */
  strategy: {
    awarenessLevel: string;
    primaryEmotion: string;
    avatar: string;
    hypothesis: string;
    coreCreativeIdea: string;
    /** Present only when a promotion is running in this batch. */
    offer?: {
      promo: string;
      valueCallout: string;
      fourthHook: string;
      urgency: string;
    };
    production: {
      format: string;
      creator: string;
      props: string;
      locations: string;
    };
    editing: {
      pacing: string;
      graphics: string;
      audio: string;
    };
    /** Present only when an Inspiration Bank example is pinned to the task. */
    reference?: {
      adaptationNote: string;
    };
  };
}

/** Dot-paths of the regenerable document fields (the editor's ↻ targets). */
export type UgcDocFieldPath =
  | 'briefInfo.collection'
  | 'briefInfo.socks'
  | 'briefInfo.format'
  | 'briefInfo.creatorRequirement'
  | 'briefInfo.creatorNote'
  | 'scriptNote'
  | 'beforeYouSubmit'
  | 'strategy.primaryEmotion'
  | 'strategy.avatar'
  | 'strategy.hypothesis'
  | 'strategy.coreCreativeIdea'
  | 'strategy.offer.promo'
  | 'strategy.offer.valueCallout'
  | 'strategy.offer.fourthHook'
  | 'strategy.offer.urgency'
  | 'strategy.production.format'
  | 'strategy.production.creator'
  | 'strategy.production.props'
  | 'strategy.production.locations'
  | 'strategy.editing.pacing'
  | 'strategy.editing.graphics'
  | 'strategy.editing.audio'
  | 'strategy.reference.adaptationNote';

/** Human labels for the document fields (editor + regen prompts). */
export const UGC_DOC_FIELD_LABELS: Record<UgcDocFieldPath, string> = {
  'briefInfo.collection': 'Collection',
  'briefInfo.socks': 'Socks',
  'briefInfo.format': 'Format',
  'briefInfo.creatorRequirement': 'Creator requirement',
  'briefInfo.creatorNote': 'Creator note',
  scriptNote: 'Script-tab creator note',
  beforeYouSubmit: 'Before you submit',
  'strategy.primaryEmotion': 'Primary emotion',
  'strategy.avatar': 'Avatar',
  'strategy.hypothesis': 'Hypothesis',
  'strategy.coreCreativeIdea': 'Core creative idea',
  'strategy.offer.promo': 'Offer — promo',
  'strategy.offer.valueCallout': 'Offer — value callout',
  'strategy.offer.fourthHook': 'Offer — fourth hook',
  'strategy.offer.urgency': 'Offer — urgency',
  'strategy.production.format': 'Production — format',
  'strategy.production.creator': 'Production — creator',
  'strategy.production.props': 'Production — props',
  'strategy.production.locations': 'Production — locations',
  'strategy.editing.pacing': 'Editing — pacing',
  'strategy.editing.graphics': 'Editing — graphics',
  'strategy.editing.audio': 'Editing — audio',
  'strategy.reference.adaptationNote': 'Reference — adaptation note',
};

/** Fields whose value is a list (rendered one paragraph / bullet per item;
 *  regenerated as newline-separated text). */
export const UGC_DOC_LIST_FIELDS: ReadonlySet<UgcDocFieldPath> = new Set<UgcDocFieldPath>([
  'briefInfo.creatorNote',
  'beforeYouSubmit',
]);

export function getUgcDocField(doc: UgcCreatorDoc, path: UgcDocFieldPath): string | string[] | undefined {
  let cur: unknown = doc;
  for (const key of path.split('.')) {
    if (cur === null || typeof cur !== 'object') return undefined;
    cur = (cur as Record<string, unknown>)[key];
  }
  return cur as string | string[] | undefined;
}

/** Returns a NEW doc with the field set (creates the optional offer /
 *  reference groups on demand). */
export function setUgcDocField(doc: UgcCreatorDoc, path: UgcDocFieldPath, value: string | string[]): UgcCreatorDoc {
  const next = JSON.parse(JSON.stringify(doc)) as UgcCreatorDoc;
  const keys = path.split('.');
  let cur = next as unknown as Record<string, unknown>;
  for (const key of keys.slice(0, -1)) {
    if (cur[key] === undefined || cur[key] === null || typeof cur[key] !== 'object') cur[key] = {};
    cur = cur[key] as Record<string, unknown>;
  }
  cur[keys[keys.length - 1]] = value;
  return next;
}

// ─── Brief → document ───────────────────────────────────────────────────────

/** Product display names as the example writes them. */
export function ugcProductLabel(product: string): string {
  switch (product) {
    case 'EasyStretch':
      return 'Viasox EasyStretch™ Socks';
    case 'Compression':
      return 'Viasox Compression Socks';
    case 'Ankle Compression':
      return 'Viasox Ankle Compression Socks';
    default:
      return `Viasox ${product}`;
  }
}

export function ugcDurationLabel(duration: string): string {
  switch (duration) {
    case '1-15 sec':
      return '1–15 seconds';
    case '16-59 sec':
      return '16–59 seconds';
    case '60-90 sec':
      return '60–90 seconds';
    default:
      return duration;
  }
}

/** Main-edit rows only (before the end card): the hook 1 row, the body, the
 *  CTA row. Alternate-take rows are represented by the hooks list instead. */
function mainEditRows(brief: UgcBriefV2): V2Row[] {
  const endIdx = brief.storyboard.findIndex((r) => r.clipNumber === 'end-card');
  return endIdx === -1 ? brief.storyboard : brief.storyboard.slice(0, endIdx);
}

/** The script table rows: HOOK 1..N (each hook is its own take, sharing the
 *  hook clip's shot direction unless its alternate-take row carries its own),
 *  then BODY 1..n, OFFER (when a row is marked), CTA. */
export function buildScriptRows(brief: UgcBriefV2): UgcScriptRow[] {
  const rows = mainEditRows(brief);
  const primaryHookId = brief.hooks[0]?.id;
  const primaryCtaId = brief.ctas[0]?.id;
  const hookRow = rows.find((r) => r.mirrorsLineId === primaryHookId) ?? rows[0];
  const ctaRow = rows.find((r) => r.mirrorsLineId === primaryCtaId);
  const out: UgcScriptRow[] = [];

  brief.hooks.forEach((h, i) => {
    const takeRow = i === 0 ? hookRow : brief.storyboard.find((r) => r.mirrorsLineId === h.id);
    const shot = (takeRow?.shotDescription ?? hookRow?.shotDescription ?? '').replace(/^Same setup as clip 1\.\s*/i, '');
    const overlay = takeRow?.overlayText ?? (i === 0 ? hookRow?.overlayText : '') ?? '';
    out.push({
      label: `HOOK ${i + 1}${i === brief.hooks.length - 1 && brief.hooks.length === 4 && /\b(sale|free|offer|anniversary|deal)\b/i.test(h.text) && hasOffer(brief) ? ' — SALE FIRST' : ''}`,
      shot,
      line: h.text,
      overlay,
    });
  });

  let bodyNo = 0;
  let productSeen = false;
  for (const r of rows) {
    if (r === hookRow || r.mirrorsLineId === primaryHookId) continue;
    if (r === ctaRow || r.mirrorsLineId === primaryCtaId) continue;
    if (r.isOffer) {
      out.push({ label: 'OFFER', shot: r.shotDescription, line: r.scriptLine, overlay: r.overlayText ?? '' });
      continue;
    }
    bodyNo += 1;
    const reveal = !productSeen && r.isProductReveal;
    if (reveal) productSeen = true;
    out.push({
      label: `BODY ${bodyNo}${reveal ? ' — PRODUCT REVEAL' : ''}`,
      shot: r.shotDescription,
      line: r.scriptLine,
      overlay: r.overlayText ?? '',
    });
  }
  if (ctaRow) {
    out.push({ label: 'CTA', shot: ctaRow.shotDescription, line: ctaRow.scriptLine, overlay: ctaRow.overlayText ?? '' });
  } else if (brief.ctas[0]) {
    out.push({ label: 'CTA', shot: '', line: brief.ctas[0].text, overlay: '' });
  }
  return out;
}

function hasOffer(brief: UgcBriefV2): boolean {
  return Boolean(brief.creatorDoc?.strategy.offer?.promo);
}

/** Map a finished UGC brief onto the three-tab document. Throws for ecom
 *  briefs (they keep their own export) and for briefs written before the
 *  document layer existed (no `creatorDoc`). */
export function buildUgcDocument(brief: UgcBriefV2): UgcDocument {
  if (taskAdType(brief.task) === 'ecom') throw new Error('The three-tab creator document is UGC-only.');
  const doc = brief.creatorDoc;
  if (!doc) {
    throw new Error(
      'This brief was written before the three-tab document format existed and has no document fields. Regenerate it (or use "Rework story") to get the new format.',
    );
  }
  const title = brief.taskName;

  const creatorBrief: UgcDocTab = {
    title: 'Creator Brief',
    blocks: [
      { kind: 'title', text: 'Creator Brief' },
      { kind: 'heading', text: 'BRIEF INFO' },
      { kind: 'paragraph', text: '' },
      {
        kind: 'kvTable',
        rows: [
          { label: 'Brief ID', value: [title] },
          { label: 'Product', value: [ugcProductLabel(brief.task.product)] },
          { label: 'Collection', value: [doc.briefInfo.collection] },
          { label: 'Socks', value: [doc.briefInfo.socks] },
          { label: 'Format', value: [doc.briefInfo.format] },
          { label: 'Creator Requirement', value: [doc.briefInfo.creatorRequirement] },
          { label: 'Creator Note', value: interleaveBlank(doc.briefInfo.creatorNote) },
          { label: 'Duration', value: [ugcDurationLabel(brief.task.duration)] },
        ],
      },
    ],
  };

  const script: UgcDocTab = {
    title: 'Script',
    blocks: [
      { kind: 'title', text: 'Script' },
      { kind: 'heading', text: 'CREATOR NOTE' },
      { kind: 'paragraph', text: doc.scriptNote },
      { kind: 'paragraph', text: '' },
      { kind: 'readThroughLabel', text: 'SCRIPT — FULL READ-THROUGH' },
      { kind: 'readThrough', text: brief.scriptProse },
      { kind: 'heading', text: 'SCRIPT' },
      { kind: 'paragraph', text: '' },
      {
        kind: 'scriptTable',
        header: ['LINE / SECTION', 'SHOT / ACTION', 'SCRIPT LINE', 'ON-SCREEN TEXT'],
        rows: buildScriptRows(brief),
      },
      { kind: 'heading', text: 'BEFORE YOU SUBMIT' },
      { kind: 'bullets', items: doc.beforeYouSubmit },
    ],
  };

  const groups: UgcStrategyGroup[] = [
    {
      section: 'Strategy',
      fields: [
        { field: 'Awareness Level', direction: doc.strategy.awarenessLevel },
        { field: 'Primary Emotion', direction: doc.strategy.primaryEmotion },
        { field: 'Avatar', direction: doc.strategy.avatar },
        { field: 'Hypothesis', direction: doc.strategy.hypothesis },
        { field: 'Core Creative Idea', direction: doc.strategy.coreCreativeIdea },
      ],
    },
  ];
  if (doc.strategy.offer?.promo) {
    groups.push({
      section: 'Offer',
      fields: [
        { field: 'Promo', direction: doc.strategy.offer.promo },
        { field: 'Value Callout', direction: doc.strategy.offer.valueCallout },
        { field: 'Fourth Hook', direction: doc.strategy.offer.fourthHook },
        { field: 'Urgency', direction: doc.strategy.offer.urgency },
      ],
    });
  }
  groups.push(
    {
      section: 'Production',
      fields: [
        { field: 'Format', direction: doc.strategy.production.format },
        { field: 'Creator', direction: doc.strategy.production.creator },
        { field: 'Props', direction: doc.strategy.production.props },
        { field: 'Locations', direction: doc.strategy.production.locations },
      ],
    },
    {
      section: 'Editing',
      fields: [
        { field: 'Pacing', direction: doc.strategy.editing.pacing },
        { field: 'Graphics', direction: doc.strategy.editing.graphics },
        { field: 'Audio', direction: doc.strategy.editing.audio },
      ],
    },
  );
  if (doc.strategy.reference?.adaptationNote) {
    groups.push({ section: 'Reference', fields: [{ field: 'Adaptation Note', direction: doc.strategy.reference.adaptationNote }] });
  }

  const strategy: UgcDocTab = {
    title: 'Strategy',
    blocks: [
      { kind: 'title', text: 'Strategy' },
      { kind: 'heading', text: 'STRATEGY' },
      { kind: 'paragraph', text: '' },
      { kind: 'strategyTable', header: ['SECTION', 'FIELD', 'DIRECTION'], groups },
    ],
  };

  return { title, tabs: [creatorBrief, script, strategy] };
}

/** ["a","b","c"] → ["a","","b","","c"] — blank paragraphs between, as in the example. */
function interleaveBlank(paragraphs: string[]): string[] {
  const out: string[] = [];
  paragraphs.forEach((p, i) => {
    if (i > 0) out.push('');
    out.push(p);
  });
  return out.length ? out : [''];
}

/** A sample document with the example's real content — the fixture both
 *  renderers are verified against (render it, compare with the example). */
export function exampleUgcDocument(): UgcDocument {
  return {
    title: 'SOX-1592_ES_Viasox Anniversary',
    tabs: [
      {
        title: 'Creator Brief',
        blocks: [
          { kind: 'title', text: 'Creator Brief' },
          { kind: 'heading', text: 'BRIEF INFO' },
          { kind: 'paragraph', text: '' },
          {
            kind: 'kvTable',
            rows: [
              { label: 'Brief ID', value: ['SOX-1592_ES_Viasox Anniversary'] },
              { label: 'Product', value: ['Viasox EasyStretch™ Socks'] },
              { label: 'Collection', value: ['EasyStretch™'] },
              { label: 'Socks', value: ['2 Easystretch SocksLegacy and Snoopy Pattern.'] },
              { label: 'Format', value: ['9:16 creator-filmed UGC demonstration + testimonial'] },
              {
                label: 'Creator Requirement',
                value: ['Female, 50+, North American; naturally fuller/wider calves and genuine experience with tight sock cuffs, sock marks, or end-of-day puffiness'],
              },
              {
                label: 'Creator Note',
                value: [
                  'Hi! This video should feel like a personal discovery filmed at home, built around one repeatable visual: mapping what tight socks do to wider calves. Use a washable, skin-safe marker—not a permanent Sharpie—to draw the cuff line and label the areas where a regular sock digs in, leaves marks, or makes your legs / feet feel puffy. Keep the drawings simple and readable on camera.',
                  '',
                  'Please record all four hooks as separate takes. Each hook connects to the same shared body and CTA. Hook 4 must begin with the Viasox anniversary sale so it can also be edited into a shorter sale-led video.',
                  '',
                  'Have a narrow/tight unbranded sock, a flexible measuring tape or ruler, and at least two patterned EasyStretch™ pairs ready. Capture clear close-ups of the old cuff mark, the comparison sock opening, the EasyStretch™ opening at rest and stretched, the non-binding top resting on your calf, and one uninterrupted pull-on demonstration. Also film the triple-padded bottom, seamless toe area, both patterns, and natural walking/standing lifestyle clips.',
                  '',
                  'Speak naturally rather than reading word-for-word. Any statement about swelling, marks, discomfort, or personal improvement must be true to your experience. Do not call EasyStretch™ medical compression or say it treats circulation problems. Submit raw, unedited vertical clips with clean audio, bright natural light, no filters or captions, and two seconds of silence before and after each take.',
                ],
              },
              { label: 'Duration', value: ['90–120 seconds'] },
            ],
          },
        ],
      },
      {
        title: 'Script',
        blocks: [
          { kind: 'title', text: 'Script' },
          { kind: 'heading', text: 'CREATOR NOTE' },
          {
            kind: 'paragraph',
            text: 'Film all four hooks as separate takes. Each hook connects to the same shared body and CTA. Hook 4 begins with the anniversary offer and can also be edited as a shorter sale-led cut. Keep Viasox out of frame until the product reveal in the shared body.',
          },
          { kind: 'paragraph', text: '' },
          { kind: 'readThroughLabel', text: 'SCRIPT — FULL READ-THROUGH' },
          {
            kind: 'readThrough',
            text: "If your socks leave a ring this deep around your calf, your calves are not the problem. Your socks are too small. This was my normal. The cuff would dig in right here, and by the time I took the sock off, the line was practically stamped into my leg. And being tight all over does not make an ordinary sock medical compression. For me, it was just a narrow cuff pressing into my leg and leaving everything below it feeling puffy and uncomfortable. Deep sock marks here. That squeezed, itchy feeling here. I kept buying different brands, but the opening always looked almost identical. Bigger calves were expected to squeeze into the same little cuff. Then I found Viasox EasyStretch, and the difference was obvious before I even put them on. Look at the opening on this one. It has extra-wide stretch, so instead of asking my calf to fit the sock, the sock actually opens to fit my calf. And this top is non-binding. It sits against my leg without that same tight band cutting into me. I can open it wide, get my foot in, and pull it over my calf without turning getting dressed into a workout. This is the part I care about: I don't get those same deep cuff marks anymore. My calves don't feel constantly squeezed, and my ankles don't feel nearly as puffy when I take them off. Plus, there is a triple-padded bottom under my feet and no bulky toe seam rubbing across my toes. So I can wear them through errands, travel, or a full day at home and they look like fun socks, not something I had to settle for. And right now, Viasox is celebrating its anniversary. Buy two pairs and they give you three more free. That is five pairs for the price of two. If your calves have been fighting your socks every day, stop blaming your legs. Go to Viasox.com and shop the anniversary sale: buy one, get one free, or buy two and get three free.",
          },
          { kind: 'heading', text: 'SCRIPT' },
          { kind: 'paragraph', text: '' },
          {
            kind: 'scriptTable',
            header: ['LINE / SECTION', 'SHOT / ACTION', 'SCRIPT LINE', 'ON-SCREEN TEXT'],
            rows: [
              {
                label: 'HOOK 1',
                shot: 'Start tight on your bare calf. Draw a red line exactly where a regular sock cuff usually sits, then circle the indentation.',
                line: 'If your socks leave a ring this deep around your calf, your calves are not the problem. Your socks are too small.',
                overlay: 'YOUR CALVES AREN’T THE PROBLEM',
              },
              {
                label: 'HOOK 2',
                shot: 'Wear the narrow comparison sock. Pull the cuff slightly away, let it snap back gently, then mark the squeezed area above it.',
                line: 'This tiny opening is supposed to fit all of this? No wonder I was counting the minutes until I could take my socks off.',
                overlay: 'THIS TINY OPENING?',
              },
              {
                label: 'HOOK 3',
                shot: 'Hold the narrow sock opening beside your calf and use the marker to draw a bracket showing the size mismatch.',
                line: 'I kept sizing up my socks, then ending up with loose fabric around my toes and the same tight cuff around my calf.',
                overlay: 'I WAS BLAMING MY SHOES',
              },
              {
                label: 'HOOK 4 — SALE FIRST',
                shot: 'Hold two Viasox pairs, then leave room for three animated pairs to pop in. Immediately point to the old cuff line on your calf.',
                line: 'Viasox is giving away three free pairs for its anniversary. And if regular socks dig into your calves like this, let me show you why these are worth stocking up on.',
                overlay: 'BUY 2, GET 3 FREE • ANNIVERSARY SALE',
              },
              {
                label: 'BODY 1',
                shot: 'Wear the narrow comparison sock. Trace its top edge with the skin-safe marker and write TIGHT above the line.',
                line: 'This was my normal. The cuff would dig in right here, and by the time I took the sock off, the line was practically stamped into my leg.',
                overlay: '',
              },
              {
                label: 'BODY 2',
                shot: 'Remove the sock. Draw small downward arrows toward the ankle and circle the puffy-feeling area. Optional simple pressure overlay.',
                line: 'And being tight all over does not make an ordinary sock medical compression. For me, it was just a narrow cuff pressing into my leg and leaving everything below it feeling puffy and uncomfortable.',
                overlay: '',
              },
              {
                label: 'BODY 3',
                shot: 'Point to each marked zone as you name it: cuff line, itchy skin, puffy ankle. Show a real indentation only if authentic.',
                line: 'Deep sock marks here. That squeezed, itchy feeling here. And this cuff was so tight around my calf, it was restricting circulation and causing swelling to build below it. That’s why my ankle looked puffier beneath the line.',
                overlay: '',
              },
              {
                label: 'BODY 4',
                shot: 'Hold up several ordinary socks with similarly narrow openings. Stretch one and show how quickly it pulls back.',
                line: 'I kept buying different brands, but the opening always looked almost identical. Bigger calves were expected to squeeze into the same little cuff.',
                overlay: '',
              },
              {
                label: 'BODY 5 — PRODUCT REVEAL',
                shot: 'Bring Viasox EasyStretch™ into frame for the first time. Place it beside the comparison sock.',
                line: 'Then I found Viasox EasyStretch, and the difference was obvious before I even put them on.',
                overlay: '',
              },
              {
                label: 'BODY 6',
                shot: 'Use a flexible ruler or measuring tape to compare both openings. Stretch EasyStretch™ wide, hold for two seconds, then release.',
                line: 'Look at the opening on this one. It has extra-wide stretch, so instead of asking my calf to fit the sock, the sock actually opens to fit my calf.',
                overlay: '',
              },
              {
                label: 'BODY 7',
                shot: 'Draw a green line above the red old-cuff line. Put EasyStretch™ on and show its top resting against the calf without digging.',
                line: 'And this top is non-binding. It sits against my leg without that same tight band cutting into me.',
                overlay: '',
              },
              {
                label: 'BODY 8',
                shot: 'Film one uninterrupted shot of putting the sock on. No jump cuts. Then stand and smooth it once.',
                line: 'I can open it wide, get my foot in, and pull it over my calf without turning getting dressed into a workout.',
                overlay: '',
              },
              {
                label: 'BODY 9',
                shot: 'Show the calf after wearing EasyStretch™ for a realistic period. Point back to the marker map. Only show/results state what is personally true.',
                line: 'This is the part I care about: I don’t get those same deep cuff marks anymore. My calves don’t feel constantly squeezed, and my ankles don’t feel nearly as puffy when I take them off.',
                overlay: '',
              },
              {
                label: 'BODY 10',
                shot: 'Turn the sock over and press the sole; then show the toe area and wiggle your toes.',
                line: 'Plus, there is a triple-padded bottom under my feet and no bulky toe seam rubbing across my toes. The whole sock is built around comfort.',
                overlay: '',
              },
              {
                label: 'BODY 11',
                shot: 'Walk through the house, stand in the kitchen, sit comfortably, then show two different patterns from the same camera angle.',
                line: 'So I can wear them through errands, travel, or a full day at home and they look like fun socks, not something I had to settle for.',
                overlay: '',
              },
              {
                label: 'OFFER',
                shot: 'Hold two pairs, leave room for an animated pairs.',
                line: 'And right now, Viasox is celebrating its anniversary. Buy two pairs and they give you three more free. That is five pairs for the price of two.',
                overlay: '5 PAIRS FOR THE PRICE OF 2',
              },
              {
                label: 'CTA',
                shot: 'Hold all available pairs, point down, and finish on a clean close-up of the stretched opening around your calf.',
                line: 'If your calves have been fighting your socks every day, stop blaming your legs. Go to Viasox.com and shop the anniversary sale: buy one, get one free, or buy two and get three free.',
                overlay: 'BUY 1, GET 1 FREE • BUY 2, GET 3 FREE •',
              },
            ],
          },
          { kind: 'heading', text: 'BEFORE YOU SUBMIT' },
          {
            kind: 'bullets',
            items: [
              'Film all four hooks as separate takes and keep Viasox out of frame until the shared-body product reveal.',
              'Use only a washable, skin-safe marker on the calf; do not use permanent marker.',
              'Capture the narrow-sock comparison, ruler/stretch test, uninterrupted pull-on shot, cuff fit, sole padding, toe area, patterns and lifestyle footage.',
              'Film vertically in bright natural light with clear audio; turn off HDR, filters, captions, music and in-camera effects.',
              'Keep all statements about sock marks, puffiness, discomfort and personal results truthful to your experience.',
              'Do not call EasyStretch™ compression or claim it treats circulation problems, edema or swelling.',
            ],
          },
        ],
      },
      {
        title: 'Strategy',
        blocks: [
          { kind: 'title', text: 'Strategy' },
          { kind: 'heading', text: 'STRATEGY' },
          { kind: 'paragraph', text: '' },
          {
            kind: 'strategyTable',
            header: ['SECTION', 'FIELD', 'DIRECTION'],
            groups: [
              {
                section: 'Strategy',
                fields: [
                  { field: 'Awareness Level', direction: 'Problem-aware moving toward solution-aware' },
                  { field: 'Primary Emotion', direction: 'Frustrated self-recognition → visual proof → relief → urgency' },
                  {
                    field: 'Avatar',
                    direction:
                      'North American woman 50+ with naturally wider calves who repeatedly experiences tight sock cuffs, deep sock marks, discomfort and end-of-day ankle puffiness; she assumes her legs are the problem and has not found socks that feel made for her body.',
                  },
                  {
                    field: 'Hypothesis',
                    direction:
                      'A physical calf-map demonstration will make an invisible fit problem immediately legible. Showing the narrow cuff, marking the pressure zones, and then measuring the EasyStretch™ opening turns a familiar private frustration into visible proof and positions the product as the sock designed to accommodate her calf.',
                  },
                  {
                    field: 'Core Creative Idea',
                    direction:
                      'MY CALVES WEREN’T THE PROBLEM. THE SOCKS WERE. The marker remains the visual thread: red marks identify the problem; a ruler proves the size mismatch; a green line and EasyStretch™ demonstrate the more accommodating fit.',
                  },
                ],
              },
              {
                section: 'Offer',
                fields: [
                  { field: 'Promo', direction: 'Viasox Anniversary Sale: Buy 1, Get 1 Free or Buy 2, Get 3 Free.' },
                  { field: 'Value Callout', direction: 'Pay for two pairs and receive five pairs total.' },
                  {
                    field: 'Fourth Hook',
                    direction:
                      'Must open with Buy 2, Get 3 Free, then point directly to the old cuff line. It should work both as Hook 4 for the long edit and as the opening of a shorter sale-led cut.',
                  },
                  { field: 'Urgency', direction: 'Anniversary promotion and pattern availability; confirm the live offer before export.' },
                ],
              },
              {
                section: 'Production',
                fields: [
                  { field: 'Format', direction: 'Creator-filmed UGC demonstration/testimonial; vertical 9:16; target 90–120 seconds.' },
                  { field: 'Creator', direction: 'Energetic North American woman 50+ with visibly fuller calves. Personal symptom/result statements must match her actual lived experience.' },
                  {
                    field: 'Props',
                    direction:
                      'Washable skin-safe marker, flexible ruler or measuring tape, narrow unbranded comparison sock, two or more approved patterned EasyStretch™ pairs, optional five-pair set for offer shot.',
                  },
                  {
                    field: 'Locations',
                    direction: 'Bright home setting with a chair or couch, hard floor, kitchen or hallway, and uncluttered wall/background for the calf demonstration.',
                  },
                ],
              },
              {
                section: 'Editing',
                fields: [
                  {
                    field: 'Pacing',
                    direction:
                      'Fast pattern interrupt in the first three seconds; deliberate close-ups during marker/ruler proof; faster benefit stack after product reveal; energetic sale close.',
                  },
                  {
                    field: 'Graphics',
                    direction:
                      'Use simple red pressure-zone labels before reveal and green fit/comfort labels after reveal. Add a five-pair counter for the offer. Keep captions bold and highly readable.',
                  },
                  {
                    field: 'Audio',
                    direction:
                      'Natural direct-to-camera delivery with small pauses for each drawing. Light upbeat music; lower it during the fit explanation and lift it at the sale reveal.',
                  },
                ],
              },
              {
                section: 'Reference',
                fields: [
                  {
                    field: 'Adaptation Note',
                    direction:
                      'Borrow the reference’s show-the-problem → explain-the-mechanism → demonstrate-the-product → before/after payoff structure. Replace its glass-and-liquid metaphor with a calf map, cuff comparison and ruler-based stretch demonstration. Do not carry over its health claims or product mechanism.',
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  };
}
