/**
 * Escape HTML special characters to prevent injection in exported documents.
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Converts markdown content to a basic HTML string for doc/pdf export.
 * Handles: headers, bold, italic, tables, lists, horizontal rules, paragraphs.
 */
function markdownToHtml(md: string): string {
  let html = md;

  // Escape HTML entities (except our markdown chars)
  html = html.replace(/&/g, '&amp;');
  html = html.replace(/</g, '&lt;');
  html = html.replace(/>/g, '&gt;');

  // Blockquotes — process AFTER escaping, matching the escaped ">" character
  html = html.replace(/^&gt; (.+)$/gm, '<blockquote style="border-left:4px solid #93c5fd;background:#eff6ff;padding:8px 16px;margin:12px 0;border-radius:0 8px 8px 0;font-style:italic;font-size:14px;color:#334155;">$1</blockquote>');

  // Tables — process before other rules
  html = html.replace(/^(\|.+\|)\n(\|[\s\-:|]+\|)\n((?:\|.+\|\n?)+)/gm, (_match, headerRow: string, _sepRow: string, bodyRows: string) => {
    const headers = headerRow.split('|').filter((c: string) => c.trim()).map((c: string) => `<th style="border:1px solid #ddd;padding:8px 12px;background:#f8fafc;text-align:left;font-size:13px;">${c.trim()}</th>`);
    const rows = bodyRows.trim().split('\n').map((row: string) => {
      const cells = row.split('|').filter((c: string) => c.trim()).map((c: string) => `<td style="border:1px solid #ddd;padding:8px 12px;font-size:13px;">${c.trim()}</td>`);
      return `<tr>${cells.join('')}</tr>`;
    });
    return `<table style="border-collapse:collapse;width:100%;margin:16px 0;"><thead><tr>${headers.join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`;
  });

  // Headers
  html = html.replace(/^### (.+)$/gm, '<h3 style="margin:20px 0 8px;font-size:16px;color:#1e293b;">$1</h3>');
  html = html.replace(/^## (.+)$/gm, '<h2 style="margin:24px 0 10px;font-size:20px;color:#1e293b;">$1</h2>');
  html = html.replace(/^# (.+)$/gm, '<h1 style="margin:28px 0 12px;font-size:24px;color:#0f172a;">$1</h1>');

  // Horizontal rules
  html = html.replace(/^---+$/gm, '<hr style="border:none;border-top:1px solid #e2e8f0;margin:20px 0;">');

  // Bold and italic
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');

  // Unordered lists
  html = html.replace(/^(\s*)[-*] (.+)$/gm, '$1<li style="margin:4px 0;font-size:14px;">$2</li>');
  html = html.replace(/((?:<li[^>]*>.*<\/li>\n?)+)/g, '<ul style="margin:8px 0;padding-left:24px;">$1</ul>');

  // Ordered lists — wrap consecutive <li> items from numbered patterns in <ol>
  html = html.replace(/^\d+\. (.+)$/gm, '<oli style="margin:4px 0;font-size:14px;">$1</oli>');
  html = html.replace(/((?:<oli[^>]*>.*<\/oli>\n?)+)/g, (_match, items: string) => {
    const fixed = items.replace(/<oli/g, '<li').replace(/<\/oli>/g, '</li>');
    return `<ol style="margin:8px 0;padding-left:24px;">${fixed}</ol>`;
  });

  // Paragraphs — wrap remaining text lines
  html = html.replace(/^(?!<[a-z])((?!<\/|<ul|<ol|<li|<h[1-3]|<hr|<table|<thead|<tbody|<tr|<td|<th).+)$/gm, '<p style="margin:8px 0;font-size:14px;line-height:1.6;color:#334155;">$1</p>');

  // Clean up empty paragraphs
  html = html.replace(/<p[^>]*>\s*<\/p>/g, '');

  return html;
}

function buildHtmlDocument(content: string, title: string): string {
  const safeTitle = escapeHtml(title);
  const bodyHtml = markdownToHtml(content);
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${safeTitle}</title>
<style>
  @page { margin: 1in; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    max-width: 800px;
    margin: 0 auto;
    padding: 40px;
    color: #1e293b;
    line-height: 1.6;
  }
  table { page-break-inside: avoid; }
  h1, h2, h3 { page-break-after: avoid; }
</style>
</head>
<body>
<h1 style="font-size:28px;color:#0f172a;border-bottom:2px solid #e2e8f0;padding-bottom:12px;margin-bottom:24px;">${safeTitle}</h1>
${bodyHtml}
<p style="margin-top:40px;font-size:11px;color:#94a3b8;border-top:1px solid #e2e8f0;padding-top:12px;">Generated by Viasox Marketing Intelligence</p>
</body>
</html>`;
}

/**
 * Download content as a .doc file (HTML-based, opens in Word/Google Docs)
 */
export function downloadAsDoc(content: string, title: string): void {
  const html = buildHtmlDocument(content, title);
  const blob = new Blob([html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${title.toLowerCase().replace(/\s+/g, '-')}.doc`;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Parse a production brief (markdown) and export it as a CSV
 * matching the production brief template format:
 * STRATEGY section → HOOKS section → BODY section → EXTRA B-ROLL section (AGC only)
 *
 * Works for AGC and all other video production brief types (UGC, Founder, Podcast, etc.)
 */
export function downloadProductionBriefCsv(
  markdownContent: string,
  product: string,
  adType: string,
  /**
   * Optional Asana task name (e.g., "SOX-374_ES"). When provided, the CSV
   * is downloaded with that exact filename so the file matches the task name
   * the user sees in Asana. Falls back to a generic timestamped slug if absent.
   */
  overrideTaskName?: string,
): void {
  const isAgc = adType === 'AGC (Actor Generated Content)';
  const lines = markdownContent.split('\n');
  const csv: string[][] = [];

  // Helper: escape CSV cell
  const esc = (v: string) => {
    const s = v.trim();
    if (s.includes(',') || s.includes('"') || s.includes('\n')) {
      return `"${s.replace(/"/g, '""')}"`;
    }
    return s;
  };

  // Helper: parse markdown table rows (skip header separator row)
  const parseTable = (startIdx: number): { rows: string[][]; endIdx: number } => {
    const rows: string[][] = [];
    let i = startIdx;
    while (i < lines.length) {
      const line = lines[i].trim();
      if (!line.startsWith('|')) break;
      // Skip separator rows (|---|---|...)
      if (/^\|[\s\-:|]+\|$/.test(line)) { i++; continue; }
      const cells = line.split('|').slice(1, -1).map(c => c.replace(/\*\*/g, '').trim());
      rows.push(cells);
      i++;
    }
    return { rows, endIdx: i };
  };

  // Extract strategy fields from the text between STRATEGY heading and HOOKS heading
  const extractField = (label: string): string => {
    const regex = new RegExp(`\\*\\*${label}:?\\*\\*\\s*(.+?)(?:\\n|$)`, 'i');
    const match = markdownContent.match(regex);
    return match ? match[1].replace(/\*\*/g, '').trim() : '';
  };

  // --- STRATEGY SECTION ---
  csv.push(['STRATEGY', '', '', '', '', '', '', '', '', '']);
  if (isAgc) {
    csv.push(['CONCEPT', 'ANGLE', 'AVATAR', 'LOCATION', 'PRODUCT', 'COLLECTION', 'PROMOTION', 'OFFER', '', '']);
    csv.push([
      extractField('Concept') || extractField('Hypothesis'),
      extractField('Angle'),
      extractField('Avatar') || extractField('Talent'),
      extractField('Location'),
      product,
      extractField('Collection') || extractField('Patterns'),
      extractField('Promotion') || extractField('Promo'),
      extractField('Offer'),
      '', ''
    ]);
    csv.push(['', '', '', '', '', '', '', '', '', '']);
    csv.push(['', '', '', '', '', '', '', '', '', '']);
    csv.push(['', '', '', '', '', '', '', '', '', '']);
    csv.push(['PACING', 'MUSIC', 'ASSETS', 'ADDITIONAL NOTES', '', '', 'LANDING PAGE', '', '', '']);
    csv.push([
      extractField('Pacing'),
      extractField('Music'),
      extractField('Assets'),
      extractField('Notes') || extractField('Additional Notes'),
      '', '', '', '', '', ''
    ]);
  } else {
    csv.push(['HYPOTHESIS', 'AD TYPE', 'PERSONA', 'AWARENESS', 'ANGLE', 'PRODUCT', 'LOCATION', 'OFFER', '', '']);
    csv.push([
      extractField('Hypothesis'),
      adType,
      extractField('Primary Persona') || extractField('Persona'),
      extractField('Awareness Level') || extractField('Awareness'),
      extractField('Angle'),
      product,
      extractField('Location'),
      extractField('Offer'),
      '', ''
    ]);
    csv.push(['', '', '', '', '', '', '', '', '', '']);
    csv.push(['', '', '', '', '', '', '', '', '', '']);
    csv.push(['', '', '', '', '', '', '', '', '', '']);
    csv.push(['PACING', 'MUSIC', 'TALENT', 'ADDITIONAL NOTES', '', '', '', '', '', '']);
    csv.push([
      extractField('Pacing'),
      extractField('Music'),
      extractField('Talent') || extractField('Talent Description'),
      extractField('Notes') || extractField('Additional Notes'),
      '', '', '', '', '', ''
    ]);
  }
  csv.push(['', '', '', '', '', '', '', '', '', '']);
  csv.push(['', '', '', '', '', '', '', '', '', '']);

  // --- HOOKS SECTION ---
  csv.push(['HOOKS', '', '', '', '', '', '', '', '', '']);
  csv.push(['BUILDING BLOCK', 'SHOT TYPE', 'SHOT ANGLE', 'TALENT NOTES', 'SHOT NOTES', 'SHOT VISUAL', 'LINES', 'EDITING NOTES', 'CAPTION', '']);

  // Find the hooks table in the markdown
  let hooksFound = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim().toLowerCase();
    if ((line.includes('hook') && line.includes('matrix')) || line === '### 2. 9-hook matrix' || (line.startsWith('#') && line.includes('hook'))) {
      // Skip to next table
      for (let j = i + 1; j < lines.length; j++) {
        if (lines[j].trim().startsWith('|')) {
          const { rows, endIdx } = parseTable(j);
          // Skip header row, add data rows
          for (let r = 1; r < rows.length; r++) {
            // Pad to 10 columns
            while (rows[r].length < 10) rows[r].push('');
            csv.push(rows[r].slice(0, 10));
          }
          hooksFound = true;
          i = endIdx;
          break;
        }
      }
      if (hooksFound) break;
    }
  }
  // If no hooks table found, add 9 empty rows
  if (!hooksFound) {
    for (let h = 1; h <= 9; h++) {
      csv.push([`Hook ${h}`, '', '', '', '', '', '', '', '', '']);
    }
  }

  csv.push(['', '', '', '', '', '', '', '', '', '']);

  // --- BODY SECTION ---
  csv.push(['BODY', '', '', '', '', '', '', '', '', '']);
  csv.push(['BUILDING BLOCK', 'SHOT TYPE', 'SHOT ANGLE', 'TALENT NOTES', 'SHOT NOTES', 'SHOT VISUAL', 'LINES', 'EDITING NOTES', 'CAPTION', '']);

  let bodyFound = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim().toLowerCase();
    if ((line.startsWith('#') && line.includes('body')) && !line.includes('b-roll') && !line.includes('extra')) {
      for (let j = i + 1; j < lines.length; j++) {
        if (lines[j].trim().startsWith('|')) {
          const { rows, endIdx } = parseTable(j);
          for (let r = 1; r < rows.length; r++) {
            // Body table may have # column first — skip it if first cell is just a number
            let row = rows[r];
            if (/^\d+$/.test(row[0].trim())) {
              row = row.slice(1);
            }
            while (row.length < 10) row.push('');
            csv.push(row.slice(0, 10));
          }
          bodyFound = true;
          i = endIdx;
          break;
        }
      }
      if (bodyFound) break;
    }
  }

  csv.push(['', '', '', '', '', '', '', '', '', '']);

  // --- EXTRA B-ROLL SECTION ---
  csv.push(['EXTRA / MUST HAVE B-ROLL LIST', '', '', '', '', '', '', '', '', '']);
  csv.push(['BUILDING BLOCK', 'SHOT TYPE', 'SHOT ANGLE', 'TALENT NOTES', 'SHOT NOTES', 'SHOT VISUAL', 'LINES', 'EDITING NOTES', 'CAPTION', '']);

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim().toLowerCase();
    if ((line.startsWith('#') && line.includes('b-roll')) || (line.startsWith('#') && line.includes('extra'))) {
      for (let j = i + 1; j < lines.length; j++) {
        if (lines[j].trim().startsWith('|')) {
          const { rows, endIdx } = parseTable(j);
          for (let r = 1; r < rows.length; r++) {
            let row = rows[r];
            if (/^\d+$/.test(row[0].trim())) {
              row = row.slice(1);
            }
            while (row.length < 10) row.push('');
            csv.push(row.slice(0, 10));
          }
          i = endIdx;
          break;
        }
      }
      break;
    }
  }

  // Build CSV string
  const csvString = csv.map(row => row.map(esc).join(',')).join('\n');
  const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  if (overrideTaskName && overrideTaskName.trim().length > 0) {
    // Mirror the task name exactly — the user wants the file to match the
    // Asana task ID (e.g., "SOX-374_ES.csv"). Strip only OS-illegal chars.
    const safe = overrideTaskName.trim().replace(/[\\/:*?"<>|]/g, '_');
    a.download = `${safe}.csv`;
  } else {
    const typeSlug = adType.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/, '');
    a.download = `${typeSlug}-brief-${product.toLowerCase()}-${Date.now()}.csv`;
  }
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Parse a markdown key-value table (| Field | Value | format) into an object
 */
export function parseKvTable(markdown: string, sectionHeader: string): Record<string, string> {
  const result: Record<string, string> = {};
  const headerPattern = new RegExp(`###?\\s*\\d*\\.?\\s*${sectionHeader}`, 'i');
  const headerIdx = markdown.split('\n').findIndex(l => headerPattern.test(l));
  if (headerIdx < 0) return result;
  const lines = markdown.split('\n').slice(headerIdx + 1);
  for (const line of lines) {
    if (!line.trim().startsWith('|')) {
      if (line.trim().startsWith('#') && line.trim() !== '') break;
      continue;
    }
    if (/^\|[\s\-:|]+\|$/.test(line.trim())) continue;
    const cells = line.split('|').filter(c => c.trim()).map(c => c.replace(/\*\*/g, '').trim());
    if (cells.length >= 2 && cells[0] !== 'Field') {
      result[cells[0]] = cells[1];
    }
  }
  return result;
}

/**
 * Parse a markdown script table (| # | Shot Type | Visual | Line |) into rows
 */
export function parseScriptTable(markdown: string, sectionHeader: string): string[][] {
  const rows: string[][] = [];
  const headerPattern = new RegExp(`###?\\s*\\d*\\.?\\s*${sectionHeader}`, 'i');
  const headerIdx = markdown.split('\n').findIndex(l => headerPattern.test(l));
  if (headerIdx < 0) return rows;
  const lines = markdown.split('\n').slice(headerIdx + 1);
  let inTable = false;
  for (const line of lines) {
    if (!line.trim().startsWith('|')) {
      if (inTable) break;
      if (line.trim().startsWith('#') && line.trim() !== '') break;
      continue;
    }
    if (/^\|[\s\-:|]+\|$/.test(line.trim())) { inTable = true; continue; }
    const cells = line.split('|').filter(c => c.trim()).map(c => c.replace(/\*\*/g, '').trim());
    // Skip header row
    if (cells[0] === '#' || cells[0] === 'Hook' || cells[0] === 'Line #') { inTable = true; continue; }
    if (cells.length >= 3) {
      inTable = true;
      rows.push(cells);
    }
  }
  return rows;
}

/**
 * Download an Ecom brief as a styled .doc matching the Ecom Ad Template format
 */
export function downloadEcomBriefDoc(markdownContent: string, overrideBriefId?: string): void {
  const esc = escapeHtml;

  // Parse all sections
  const briefInfo = parseKvTable(markdownContent, 'BRIEF INFO');
  const strategy = parseKvTable(markdownContent, 'STRATEGY');
  const offer = parseKvTable(markdownContent, 'OFFER');
  const editing = parseKvTable(markdownContent, 'EDITING INSTRUCTIONS');
  const hooks = parseScriptTable(markdownContent, 'SCRIPT \\(HOOKS\\)');
  const body = parseScriptTable(markdownContent, 'SCRIPT \\(BODY\\)');

  // Use override ID (from Asana task name) or fall back to parsed Brief ID
  const briefId = overrideBriefId || briefInfo['Brief ID'] || 'ECOM_BRIEF';

  // ── Style constants matching E319.docx template exactly ──────────────
  // Font: Arial, 10pt body / 12pt section headers / 16pt title
  // Navy label cells: #1b365d with white bold text
  // Light gray borders: #bfbfbf
  // Cell padding: 80 top/bottom, 120 left/right (DXA) ≈ 6px 10px
  const NAVY = '#1b365d';
  const BORDER = '#bfbfbf';

  const sectionHeaderStyle = `padding:6px 10px;font-weight:bold;font-size:12pt;color:#000;font-family:Arial,sans-serif;`;
  const labelCellStyle = `background:${NAVY};padding:6px 10px;font-weight:bold;font-size:10pt;color:#ffffff;border:1px solid ${BORDER};width:160px;vertical-align:top;font-family:Arial,sans-serif;`;
  const valueCellStyle = `padding:6px 10px;font-size:10pt;color:#000;border:1px solid ${BORDER};vertical-align:top;font-family:Arial,sans-serif;`;
  const scriptHeaderStyle = `background:${NAVY};padding:6px 10px;font-weight:bold;font-size:10pt;color:#ffffff;border:1px solid ${BORDER};text-align:left;font-family:Arial,sans-serif;`;
  const scriptCellStyle = `padding:6px 10px;font-size:10pt;color:#000;border:1px solid ${BORDER};vertical-align:top;font-family:Arial,sans-serif;`;

  const kvRow = (label: string, value: string) =>
    `<tr><td style="${labelCellStyle}">${esc(label)}</td><td style="${valueCellStyle}">${esc(value || '—')}</td></tr>`;

  // Build HTML
  let html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(briefId)}</title>
<style>
@page { margin: 0.75in; }
body { font-family: Arial, sans-serif; max-width: 850px; margin: 0 auto; padding: 30px; color: #000; font-size: 11pt; }
table { border-collapse: collapse; width: 100%; margin-bottom: 16px; page-break-inside: avoid; }
h1 { text-align: center; }
</style></head><body>`;

  // Title — centered, bold, 16pt
  html += `<h1 style="font-size:16pt;color:#000;margin:0 0 20px 0;font-weight:bold;font-family:Arial,sans-serif;">Ecom Ad Template</h1>`;

  // 1. BRIEF INFO
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">BRIEF INFO</p>`;
  html += `<table>`;
  html += kvRow('Brief ID', briefId);
  html += kvRow('Date', briefInfo['Date'] || '');
  html += kvRow('Product', briefInfo['Product'] || '');
  html += kvRow('Collection', briefInfo['Collection'] || '');
  html += kvRow('Collection Asset', briefInfo['Collection Asset'] || '');
  html += kvRow('Format', briefInfo['Format'] || '');
  html += `</table>`;

  // 2. STRATEGY
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">STRATEGY</p>`;
  html += `<table>`;
  html += kvRow('Awareness Level', strategy['Awareness Level'] || '');
  html += kvRow('Primary Emotion', strategy['Primary Emotion'] || '');
  html += kvRow('Avatar', strategy['Avatar'] || '');
  html += kvRow('Landing Page', strategy['Landing Page'] || '');
  html += `</table>`;

  // 3. OFFER
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">OFFER</p>`;
  html += `<table>`;
  html += kvRow('Promo', offer['Promo'] || '');
  html += kvRow('Promo Asset', offer['Promo Asset'] || '');
  html += kvRow('Value Callout', offer['Value Callout'] || '');
  html += kvRow('Urgency Element', offer['Urgency Element'] || '');
  html += `</table>`;

  // 4. EDITING INSTRUCTIONS
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">EDITING INSTRUCTIONS</p>`;
  html += `<table>`;
  html += kvRow('Pacing', editing['Pacing'] || '');
  html += kvRow('Resolution', editing['Resolution'] || '');
  html += kvRow('Caption & Graphics', editing['Caption & Graphics'] || editing['Captions'] || '');
  html += kvRow('Transitions', editing['Transitions'] || '');
  html += kvRow('Music', editing['Music'] || '');
  html += kvRow('Voiceover', editing['Voiceover'] || '');
  html += kvRow('Asset', editing['Asset'] || '');
  html += kvRow('Notes', editing['Notes'] || '');
  html += `</table>`;

  // 5. REFERENCE (if present)
  const reference = parseKvTable(markdownContent, 'REFERENCE');
  if (Object.keys(reference).length > 0) {
    html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">REFERENCE</p>`;
    html += `<table>`;
    for (const [k, v] of Object.entries(reference)) {
      html += kvRow(k, v);
    }
    html += `</table>`;
  }

  // 6. SCRIPT (HOOKS)
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">SCRIPT (HOOKS)</p>`;
  html += `<table>`;
  html += `<tr><th style="${scriptHeaderStyle}width:40px;">LINE #</th><th style="${scriptHeaderStyle}width:100px;">SHOT TYPE</th><th style="${scriptHeaderStyle}width:220px;">SUGGESTED VISUAL</th><th style="${scriptHeaderStyle}">HOOK LINE</th></tr>`;
  hooks.forEach((row) => {
    const [num, shotType, visual, line] = [row[0] || '', row[1] || '', row[2] || '', row[3] || ''];
    html += `<tr><td style="${scriptCellStyle}text-align:center;width:40px;">${esc(num)}</td><td style="${scriptCellStyle}width:100px;">${esc(shotType)}</td><td style="${scriptCellStyle}width:220px;">${esc(visual)}</td><td style="${scriptCellStyle}">${esc(line)}</td></tr>`;
  });
  if (hooks.length === 0) {
    html += `<tr><td colspan="4" style="${scriptCellStyle}text-align:center;color:#999;">No hooks parsed</td></tr>`;
  }
  html += `</table>`;

  // 7. SCRIPT (BODY)
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">SCRIPT (BODY)</p>`;
  html += `<table>`;
  html += `<tr><th style="${scriptHeaderStyle}width:40px;">LINE #</th><th style="${scriptHeaderStyle}width:100px;">SHOT TYPE</th><th style="${scriptHeaderStyle}width:220px;">SUGGESTED VISUAL</th><th style="${scriptHeaderStyle}">SCRIPT LINE</th></tr>`;
  body.forEach((row) => {
    const [num, shotType, visual, line] = [row[0] || '', row[1] || '', row[2] || '', row[3] || ''];
    html += `<tr><td style="${scriptCellStyle}text-align:center;width:40px;">${esc(num)}</td><td style="${scriptCellStyle}width:100px;">${esc(shotType)}</td><td style="${scriptCellStyle}width:220px;">${esc(visual)}</td><td style="${scriptCellStyle}">${esc(line)}</td></tr>`;
  });
  if (body.length === 0) {
    html += `<tr><td colspan="4" style="${scriptCellStyle}text-align:center;color:#999;">No body rows parsed</td></tr>`;
  }
  html += `</table>`;

  html += `<p style="margin-top:30px;font-size:9pt;color:#999;border-top:1px solid #ddd;padding-top:8px;font-family:Arial,sans-serif;">Generated by Viasox Marketing Intelligence</p>`;
  html += `</body></html>`;

  const blob = new Blob([html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  // Strip only OS-illegal chars; preserve casing, hyphens, and underscores so
  // the file name matches the Asana task ID exactly (e.g., "SOX-374_ES.doc").
  const safeBriefId = briefId.replace(/[\\/:*?"<>|]/g, '_');
  a.download = `${safeBriefId}.doc`;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Download content as PDF using a print-to-PDF approach
 */
export function downloadAsPdf(content: string, title: string): void {
  const html = buildHtmlDocument(content, title);
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    // Fallback: if popup blocked, download as HTML with .pdf suggestion
    alert('Pop-up blocked. Please allow pop-ups to generate PDF, or use the .doc download option.');
    return;
  }
  printWindow.document.write(html);
  printWindow.document.close();

  // Use a flag to prevent double print() invocation
  let printed = false;
  const triggerPrint = () => {
    if (printed) return;
    printed = true;
    printWindow.print();
  };

  // Wait for content to render, then trigger print (Save as PDF)
  printWindow.onload = triggerPrint;
  // Fallback for browsers where onload doesn't fire on document.write
  setTimeout(triggerPrint, 500);
}
