/**
 * Escape HTML special characters to prevent injection in exported documents.
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Converts markdown content to a basic HTML string for doc/pdf export.
 * Handles: headers, bold, italic, tables, lists, horizontal rules, paragraphs.
 */
function markdownToHtml(md: string): string {
  let html = md;

  // Escape HTML entities (except our markdown chars)
  html = html.replace(/&/g, '&amp;');
  html = html.replace(/</g, '&lt;');
  html = html.replace(/>/g, '&gt;');

  // Blockquotes — process AFTER escaping, matching the escaped ">" character
  html = html.replace(/^&gt; (.+)$/gm, '<blockquote style="border-left:4px solid #93c5fd;background:#eff6ff;padding:8px 16px;margin:12px 0;border-radius:0 8px 8px 0;font-style:italic;font-size:14px;color:#334155;">$1</blockquote>');

  // Tables — process before other rules
  html = html.replace(/^(\|.+\|)\n(\|[\s\-:|]+\|)\n((?:\|.+\|\n?)+)/gm, (_match, headerRow: string, _sepRow: string, bodyRows: string) => {
    const headers = headerRow.split('|').filter((c: string) => c.trim()).map((c: string) => `<th style="border:1px solid #ddd;padding:8px 12px;background:#f8fafc;text-align:left;font-size:13px;">${c.trim()}</th>`);
    const rows = bodyRows.trim().split('\n').map((row: string) => {
      const cells = row.split('|').filter((c: string) => c.trim()).map((c: string) => `<td style="border:1px solid #ddd;padding:8px 12px;font-size:13px;">${c.trim()}</td>`);
      return `<tr>${cells.join('')}</tr>`;
    });
    return `<table style="border-collapse:collapse;width:100%;margin:16px 0;"><thead><tr>${headers.join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`;
  });

  // Headers
  html = html.replace(/^### (.+)$/gm, '<h3 style="margin:20px 0 8px;font-size:16px;color:#1e293b;">$1</h3>');
  html = html.replace(/^## (.+)$/gm, '<h2 style="margin:24px 0 10px;font-size:20px;color:#1e293b;">$1</h2>');
  html = html.replace(/^# (.+)$/gm, '<h1 style="margin:28px 0 12px;font-size:24px;color:#0f172a;">$1</h1>');

  // Horizontal rules
  html = html.replace(/^---+$/gm, '<hr style="border:none;border-top:1px solid #e2e8f0;margin:20px 0;">');

  // Bold and italic
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');

  // Unordered lists
  html = html.replace(/^(\s*)[-*] (.+)$/gm, '$1<li style="margin:4px 0;font-size:14px;">$2</li>');
  html = html.replace(/((?:<li[^>]*>.*<\/li>\n?)+)/g, '<ul style="margin:8px 0;padding-left:24px;">$1</ul>');

  // Ordered lists — wrap consecutive <li> items from numbered patterns in <ol>
  html = html.replace(/^\d+\. (.+)$/gm, '<oli style="margin:4px 0;font-size:14px;">$1</oli>');
  html = html.replace(/((?:<oli[^>]*>.*<\/oli>\n?)+)/g, (_match, items: string) => {
    const fixed = items.replace(/<oli/g, '<li').replace(/<\/oli>/g, '</li>');
    return `<ol style="margin:8px 0;padding-left:24px;">${fixed}</ol>`;
  });

  // Paragraphs — wrap remaining text lines
  html = html.replace(/^(?!<[a-z])((?!<\/|<ul|<ol|<li|<h[1-3]|<hr|<table|<thead|<tbody|<tr|<td|<th).+)$/gm, '<p style="margin:8px 0;font-size:14px;line-height:1.6;color:#334155;">$1</p>');

  // Clean up empty paragraphs
  html = html.replace(/<p[^>]*>\s*<\/p>/g, '');

  return html;
}

function buildHtmlDocument(content: string, title: string): string {
  const safeTitle = escapeHtml(title);
  const bodyHtml = markdownToHtml(content);
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${safeTitle}</title>
<style>
  @page { margin: 1in; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    max-width: 800px;
    margin: 0 auto;
    padding: 40px;
    color: #1e293b;
    line-height: 1.6;
  }
  table { page-break-inside: avoid; }
  h1, h2, h3 { page-break-after: avoid; }
</style>
</head>
<body>
<h1 style="font-size:28px;color:#0f172a;border-bottom:2px solid #e2e8f0;padding-bottom:12px;margin-bottom:24px;">${safeTitle}</h1>
${bodyHtml}
<p style="margin-top:40px;font-size:11px;color:#94a3b8;border-top:1px solid #e2e8f0;padding-top:12px;">Generated by Viasox Marketing Intelligence</p>
</body>
</html>`;
}

/**
 * Download content as a .doc file (HTML-based, opens in Word/Google Docs)
 */
export function downloadAsDoc(content: string, title: string): void {
  const html = buildHtmlDocument(content, title);
  const blob = new Blob([html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${title.toLowerCase().replace(/\s+/g, '-')}.doc`;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Parse a production brief (markdown) and export it as a CSV
 * matching the production brief template format:
 * STRATEGY section → HOOKS section → BODY section → EXTRA B-ROLL section (AGC only)
 *
 * Works for AGC and all other video production brief types (UGC, Founder, Podcast, etc.)
 */
export function downloadProductionBriefCsv(
  markdownContent: string,
  product: string,
  adType: string,
  /**
   * Optional Asana task name (e.g., "SOX-374_ES"). When provided, the CSV
   * is downloaded with that exact filename so the file matches the task name
   * the user sees in Asana. Falls back to a generic timestamped slug if absent.
   */
  overrideTaskName?: string,
): void {
  const isAgc = adType === 'AGC (Actor Generated Content)';
  const lines = markdownContent.split('\n');
  const csv: string[][] = [];

  // Helper: escape CSV cell
  const esc = (v: string) => {
    const s = v.trim();
    if (s.includes(',') || s.includes('"') || s.includes('\n')) {
      return `"${s.replace(/"/g, '""')}"`;
    }
    return s;
  };

  // Helper: parse markdown table rows (skip header separator row)
  const parseTable = (startIdx: number): { rows: string[][]; endIdx: number } => {
    const rows: string[][] = [];
    let i = startIdx;
    while (i < lines.length) {
      const line = lines[i].trim();
      if (!line.startsWith('|')) break;
      // Skip separator rows (|---|---|...)
      if (/^\|[\s\-:|]+\|$/.test(line)) { i++; continue; }
      const cells = line.split('|').slice(1, -1).map(c => c.replace(/\*\*/g, '').trim());
      rows.push(cells);
      i++;
    }
    return { rows, endIdx: i };
  };

  // Extract strategy fields from the text between STRATEGY heading and HOOKS heading
  const extractField = (label: string): string => {
    const regex = new RegExp(`\\*\\*${label}:?\\*\\*\\s*(.+?)(?:\\n|$)`, 'i');
    const match = markdownContent.match(regex);
    return match ? match[1].replace(/\*\*/g, '').trim() : '';
  };

  // --- STRATEGY SECTION ---
  csv.push(['STRATEGY', '', '', '', '', '', '', '', '', '']);
  if (isAgc) {
    csv.push(['CONCEPT', 'ANGLE', 'AVATAR', 'LOCATION', 'PRODUCT', 'COLLECTION', 'PROMOTION', 'OFFER', '', '']);
    csv.push([
      extractField('Concept') || extractField('Hypothesis'),
      extractField('Angle'),
      extractField('Avatar') || extractField('Talent'),
      extractField('Location'),
      product,
      extractField('Collection') || extractField('Patterns'),
      extractField('Promotion') || extractField('Promo'),
      extractField('Offer'),
      '', ''
    ]);
    csv.push(['', '', '', '', '', '', '', '', '', '']);
    csv.push(['', '', '', '', '', '', '', '', '', '']);
    csv.push(['', '', '', '', '', '', '', '', '', '']);
    csv.push(['PACING', 'MUSIC', 'ASSETS', 'ADDITIONAL NOTES', '', '', 'LANDING PAGE', '', '', '']);
    csv.push([
      extractField('Pacing'),
      extractField('Music'),
      extractField('Assets'),
      extractField('Notes') || extractField('Additional Notes'),
      '', '', '', '', '', ''
    ]);
  } else {
    csv.push(['HYPOTHESIS', 'AD TYPE', 'PERSONA', 'AWARENESS', 'ANGLE', 'PRODUCT', 'LOCATION', 'OFFER', '', '']);
    csv.push([
      extractField('Hypothesis'),
      adType,
      extractField('Primary Persona') || extractField('Persona'),
      extractField('Awareness Level') || extractField('Awareness'),
      extractField('Angle'),
      product,
      extractField('Location'),
      extractField('Offer'),
      '', ''
    ]);
    csv.push(['', '', '', '', '', '', '', '', '', '']);
    csv.push(['', '', '', '', '', '', '', '', '', '']);
    csv.push(['', '', '', '', '', '', '', '', '', '']);
    csv.push(['PACING', 'MUSIC', 'TALENT', 'ADDITIONAL NOTES', '', '', '', '', '', '']);
    csv.push([
      extractField('Pacing'),
      extractField('Music'),
      extractField('Talent') || extractField('Talent Description'),
      extractField('Notes') || extractField('Additional Notes'),
      '', '', '', '', '', ''
    ]);
  }
  csv.push(['', '', '', '', '', '', '', '', '', '']);
  csv.push(['', '', '', '', '', '', '', '', '', '']);

  // --- HOOKS SECTION ---
  csv.push(['HOOKS', '', '', '', '', '', '', '', '', '']);
  csv.push(['BUILDING BLOCK', 'SHOT TYPE', 'SHOT ANGLE', 'TALENT NOTES', 'SHOT NOTES', 'SHOT VISUAL', 'LINES', 'EDITING NOTES', 'CAPTION', '']);

  // Find the hooks table in the markdown
  let hooksFound = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim().toLowerCase();
    if ((line.includes('hook') && line.includes('matrix')) || line === '### 2. 9-hook matrix' || (line.startsWith('#') && line.includes('hook'))) {
      // Skip to next table
      for (let j = i + 1; j < lines.length; j++) {
        if (lines[j].trim().startsWith('|')) {
          const { rows, endIdx } = parseTable(j);
          // Skip header row, add data rows
          for (let r = 1; r < rows.length; r++) {
            // Pad to 10 columns
            while (rows[r].length < 10) rows[r].push('');
            csv.push(rows[r].slice(0, 10));
          }
          hooksFound = true;
          i = endIdx;
          break;
        }
      }
      if (hooksFound) break;
    }
  }
  // If no hooks table found, add 9 empty rows
  if (!hooksFound) {
    for (let h = 1; h <= 9; h++) {
      csv.push([`Hook ${h}`, '', '', '', '', '', '', '', '', '']);
    }
  }

  csv.push(['', '', '', '', '', '', '', '', '', '']);

  // --- BODY SECTION ---
  csv.push(['BODY', '', '', '', '', '', '', '', '', '']);
  csv.push(['BUILDING BLOCK', 'SHOT TYPE', 'SHOT ANGLE', 'TALENT NOTES', 'SHOT NOTES', 'SHOT VISUAL', 'LINES', 'EDITING NOTES', 'CAPTION', '']);

  let bodyFound = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim().toLowerCase();
    if ((line.startsWith('#') && line.includes('body')) && !line.includes('b-roll') && !line.includes('extra')) {
      for (let j = i + 1; j < lines.length; j++) {
        if (lines[j].trim().startsWith('|')) {
          const { rows, endIdx } = parseTable(j);
          for (let r = 1; r < rows.length; r++) {
            // Body table may have # column first — skip it if first cell is just a number
            let row = rows[r];
            if (/^\d+$/.test(row[0].trim())) {
              row = row.slice(1);
            }
            while (row.length < 10) row.push('');
            csv.push(row.slice(0, 10));
          }
          bodyFound = true;
          i = endIdx;
          break;
        }
      }
      if (bodyFound) break;
    }
  }

  csv.push(['', '', '', '', '', '', '', '', '', '']);

  // --- EXTRA B-ROLL SECTION ---
  csv.push(['EXTRA / MUST HAVE B-ROLL LIST', '', '', '', '', '', '', '', '', '']);
  csv.push(['BUILDING BLOCK', 'SHOT TYPE', 'SHOT ANGLE', 'TALENT NOTES', 'SHOT NOTES', 'SHOT VISUAL', 'LINES', 'EDITING NOTES', 'CAPTION', '']);

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim().toLowerCase();
    if ((line.startsWith('#') && line.includes('b-roll')) || (line.startsWith('#') && line.includes('extra'))) {
      for (let j = i + 1; j < lines.length; j++) {
        if (lines[j].trim().startsWith('|')) {
          const { rows, endIdx } = parseTable(j);
          for (let r = 1; r < rows.length; r++) {
            let row = rows[r];
            if (/^\d+$/.test(row[0].trim())) {
              row = row.slice(1);
            }
            while (row.length < 10) row.push('');
            csv.push(row.slice(0, 10));
          }
          i = endIdx;
          break;
        }
      }
      break;
    }
  }

  // Build CSV string
  const csvString = csv.map(row => row.map(esc).join(',')).join('\n');
  const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  if (overrideTaskName && overrideTaskName.trim().length > 0) {
    // Mirror the task name exactly — the user wants the file to match the
    // Asana task ID (e.g., "SOX-374_ES.csv"). Strip only OS-illegal chars.
    const safe = overrideTaskName.trim().replace(/[\\/:*?"<>|]/g, '_');
    a.download = `${safe}.csv`;
  } else {
    const typeSlug = adType.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/, '');
    a.download = `${typeSlug}-brief-${product.toLowerCase()}-${Date.now()}.csv`;
  }
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Parse a markdown key-value table (| Field | Value | format) into an object
 */
export function parseKvTable(markdown: string, sectionHeader: string): Record<string, string> {
  const result: Record<string, string> = {};
  const headerPattern = new RegExp(`###?\\s*\\d*\\.?\\s*${sectionHeader}`, 'i');
  const headerIdx = markdown.split('\n').findIndex(l => headerPattern.test(l));
  if (headerIdx < 0) return result;
  const lines = markdown.split('\n').slice(headerIdx + 1);
  for (const line of lines) {
    if (!line.trim().startsWith('|')) {
      if (line.trim().startsWith('#') && line.trim() !== '') break;
      continue;
    }
    if (/^\|[\s\-:|]+\|$/.test(line.trim())) continue;
    const cells = line.split('|').filter(c => c.trim()).map(c => c.replace(/\*\*/g, '').trim());
    if (cells.length >= 2 && cells[0] !== 'Field') {
      result[cells[0]] = cells[1];
    }
  }
  return result;
}

/**
 * Parse a markdown script table into rows of cells.
 *
 * IMPORTANT: preserves INNER empty cells. A markdown row like
 * `| 1 |  | Visual | Line |` has an empty 2nd cell; dropping it (as the
 * old `.filter(c => c.trim())` did) would shift every subsequent cell one
 * position left and silently corrupt the column alignment. We only strip
 * the two OUTER empties (the artifacts before the first `|` and after the
 * last `|`), never inner ones. Column alignment is then preserved exactly
 * as the model wrote it, and the downstream normalizer handles any
 * shape drift deterministically.
 */
export function parseScriptTable(markdown: string, sectionHeader: string): string[][] {
  const rows: string[][] = [];
  const headerPattern = new RegExp(`###?\\s*\\d*\\.?\\s*${sectionHeader}`, 'i');
  const headerIdx = markdown.split('\n').findIndex(l => headerPattern.test(l));
  if (headerIdx < 0) return rows;
  const lines = markdown.split('\n').slice(headerIdx + 1);
  let inTable = false;
  for (const line of lines) {
    if (!line.trim().startsWith('|')) {
      if (inTable) break;
      if (line.trim().startsWith('#') && line.trim() !== '') break;
      continue;
    }
    if (/^\|[\s\-:|]+\|$/.test(line.trim())) { inTable = true; continue; }

    // Split on the pipe delimiter, then strip ONLY the outer empties.
    const parts = line.split('|');
    if (parts.length && parts[0].trim() === '') parts.shift();
    if (parts.length && parts[parts.length - 1].trim() === '') parts.pop();
    const cells = parts.map(c => c.replace(/\*\*/g, '').trim());

    // Skip header row (the line that names the columns)
    const c0 = (cells[0] || '').toLowerCase();
    if (c0 === '#' || c0 === 'hook' || c0 === 'line #' || c0 === 'line#') { inTable = true; continue; }
    if (cells.length >= 2) {
      inTable = true;
      rows.push(cells);
    }
  }
  return rows;
}

// ─── Defensive row normalizer ──────────────────────────────────────────
//
// Sometimes the LLM produces a table whose column shape doesn't match
// the brief's actual ad type (e.g., a UGC-shaped 3-col table inside an
// Ecom-typed brief). When that drift hits a renderer that blindly assumes
// the expected shape (`row[0] || ''` etc.), the data shifts one column
// to the wrong side and the LINES column ends up empty even though the
// model wrote the spoken lines correctly.
//
// This helper accepts a parsed row + a target shape and reorders the cells
// to fill the target slots. It detects drift by:
//   - looking for UGC column-header values that leaked into a data row
//     (e.g., a row whose cells are literally "Shot Visuals", "Shot Type",
//     "Lines") — those rows get skipped
//   - inspecting whether the first cell looks like a line number (short
//     digit run) vs a long descriptive sentence. If the first cell is a
//     description, the row is treated as UGC-shaped (Visual | ShotType |
//     Lines) instead of Ecom-shaped (# | ShotType | Visual | Lines)
//
// Returns `null` for rows that should be skipped (header leaks, blanks).
// Otherwise returns a normalized 4-slot record. `driftDetected` is set
// so the renderer can warn in the console — useful for catching the
// problem in real time on future briefs.

export interface NormalizedScriptRow {
  num: string;
  shotType: string;
  visual: string;
  line: string;
  driftDetected: boolean;
}

/** Returns true if the row's cells look like UGC column-header words leaked
 *  into the table body (e.g. ["Shot Visuals", "Shot Type", "Lines"]). */
function isLeakedHeaderRow(cells: string[]): boolean {
  const lowered = cells.map((c) => c.toLowerCase().trim());
  const set = new Set(lowered);
  // Any combination of two-or-more UGC header names indicates a leaked header.
  const ugcHeaderWords = new Set(['shot visuals', 'shot type', 'lines', 'line', 'hook line', 'script line', 'voiceover', 'hook style', 'suggested visual']);
  let matches = 0;
  for (const w of set) if (ugcHeaderWords.has(w)) matches++;
  return matches >= 2 && cells.every((c) => c.trim().length < 25);
}

/** Returns true if a string looks like a short ordinal/line number (1, 2, 12...). */
function looksLikeLineNumber(s: string): boolean {
  return /^\d{1,3}$/.test(s.trim());
}

/**
 * Normalize a parsed table row into a stable {num, shotType, visual, line}
 * shape, robust to whatever column layout the LLM produced.
 *
 * THE CORE INVARIANT: in every brief template the tool generates, the
 * SPOKEN LINE (Script Line / Hook Line / Lines / Voiceover) is ALWAYS the
 * rightmost column, and the VISUAL is always immediately to its left.
 * This holds whether the model emitted:
 *   - the canonical Ecom shape   `# | Shot Type | Visual | Line`
 *   - a UGC shape                `Visual | Shot Type | Line`
 *   - a Full AI shape            `# | Visual | Voiceover`
 *   - or a DRIFTED shape with an extra Building-Block / beat column
 *     `# | Building Block | Shot Type | Visual | Line`  ← the bug case
 *
 * So we anchor from the RIGHT: the line is the last cell, the visual is
 * second-to-last, the shot type is third-to-last (when present). Any extra
 * columns the model inserted between the row number and the shot type
 * (e.g. a stray "Building Block" column) sit in the middle and are folded
 * away — they can NEVER push the spoken line out of the output.
 *
 * Returns `null` for rows that should be skipped (header leaks, blanks).
 */
export function normalizeBodyRow(
  row: string[],
  rowIndex: number,
  expected: 'ecom4' | 'ugc3',
): NormalizedScriptRow | null {
  const cells = (row || []).map((c) => (c ?? '').trim());

  // Drop fully-empty rows.
  if (cells.length === 0 || cells.every((c) => !c)) return null;

  // Drop rows that are the column-header names leaking into the data
  // (e.g. a literal ["Shot Visuals", "Shot Type", "Lines"] row).
  if (isLeakedHeaderRow(cells)) return null;

  const firstIsNumber = looksLikeLineNumber(cells[0] || '');
  const expectedCols = expected === 'ecom4' ? 4 : 3;
  // Drift = the model produced a different column count than the template.
  const driftDetected = cells.length !== expectedCols;
  const last = cells.length - 1;

  // ── NUMBERED TABLE (Ecom / Full AI): first cell is a line number. ──
  // Right-anchored: line = last cell, visual = second-to-last, shot type =
  // third-to-last (only when there's room between the number and the
  // visual). Extra middle columns (Building Block, etc.) are dropped.
  if (firstIsNumber) {
    const line = cells[last] || '';
    const visual = last - 1 >= 1 ? (cells[last - 1] || '') : '';
    const shotType = last - 2 >= 1 ? (cells[last - 2] || '') : '';
    return { num: cells[0], shotType, visual, line, driftDetected };
  }

  // ── NON-NUMBERED TABLE (UGC): first cell is the visual description. ──
  // visual = first, line = last, shot type = the middle cell (when there
  // are 3+ columns). Synthesize the row number from the index.
  const visual = cells[0] || '';
  const line = last >= 1 ? (cells[last] || '') : '';
  const shotType = cells.length >= 3 ? (cells[1] || '') : '';
  return { num: String(rowIndex + 1), shotType, visual, line, driftDetected };
}

/**
 * Download an Ecom brief as a styled .doc matching the Ecom Ad Template format
 */
export function downloadEcomBriefDoc(markdownContent: string, overrideBriefId?: string): void {
  const esc = escapeHtml;

  // Parse all sections
  const briefInfo = parseKvTable(markdownContent, 'BRIEF INFO');
  const strategy = parseKvTable(markdownContent, 'STRATEGY');
  const offer = parseKvTable(markdownContent, 'OFFER');
  const editing = parseKvTable(markdownContent, 'EDITING INSTRUCTIONS');
  const hooks = parseScriptTable(markdownContent, 'SCRIPT \\(HOOKS\\)');
  const body = parseScriptTable(markdownContent, 'SCRIPT \\(BODY\\)');

  // Use override ID (from Asana task name) or fall back to parsed Brief ID
  const briefId = overrideBriefId || briefInfo['Brief ID'] || 'ECOM_BRIEF';

  // ── Style constants matching E319.docx template exactly ──────────────
  // Font: Arial, 10pt body / 12pt section headers / 16pt title
  // Navy label cells: #1b365d with white bold text
  // Light gray borders: #bfbfbf
  // Cell padding: 80 top/bottom, 120 left/right (DXA) ≈ 6px 10px
  const NAVY = '#1b365d';
  const BORDER = '#bfbfbf';

  const sectionHeaderStyle = `padding:6px 10px;font-weight:bold;font-size:12pt;color:#000;font-family:Arial,sans-serif;`;
  const labelCellStyle = `background:${NAVY};padding:6px 10px;font-weight:bold;font-size:10pt;color:#ffffff;border:1px solid ${BORDER};width:160px;vertical-align:top;font-family:Arial,sans-serif;`;
  const valueCellStyle = `padding:6px 10px;font-size:10pt;color:#000;border:1px solid ${BORDER};vertical-align:top;font-family:Arial,sans-serif;`;
  const scriptHeaderStyle = `background:${NAVY};padding:6px 10px;font-weight:bold;font-size:10pt;color:#ffffff;border:1px solid ${BORDER};text-align:left;font-family:Arial,sans-serif;`;
  const scriptCellStyle = `padding:6px 10px;font-size:10pt;color:#000;border:1px solid ${BORDER};vertical-align:top;font-family:Arial,sans-serif;`;

  const kvRow = (label: string, value: string) =>
    `<tr><td style="${labelCellStyle}">${esc(label)}</td><td style="${valueCellStyle}">${esc(value || '—')}</td></tr>`;

  // Build HTML
  let html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(briefId)}</title>
<style>
@page { margin: 0.75in; }
body { font-family: Arial, sans-serif; max-width: 850px; margin: 0 auto; padding: 30px; color: #000; font-size: 11pt; }
table { border-collapse: collapse; width: 100%; margin-bottom: 16px; page-break-inside: avoid; }
h1 { text-align: center; }
</style></head><body>`;

  // Title — centered, bold, 16pt
  html += `<h1 style="font-size:16pt;color:#000;margin:0 0 20px 0;font-weight:bold;font-family:Arial,sans-serif;">Ecom Ad Template</h1>`;

  // 1. BRIEF INFO
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">BRIEF INFO</p>`;
  html += `<table>`;
  html += kvRow('Brief ID', briefId);
  html += kvRow('Date', briefInfo['Date'] || '');
  html += kvRow('Product', briefInfo['Product'] || '');
  html += kvRow('Collection', briefInfo['Collection'] || '');
  html += kvRow('Collection Asset', briefInfo['Collection Asset'] || '');
  html += kvRow('Format', briefInfo['Format'] || '');
  html += `</table>`;

  // 2. STRATEGY
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">STRATEGY</p>`;
  html += `<table>`;
  html += kvRow('Awareness Level', strategy['Awareness Level'] || '');
  html += kvRow('Primary Emotion', strategy['Primary Emotion'] || '');
  html += kvRow('Avatar', strategy['Avatar'] || '');
  html += kvRow('Landing Page', strategy['Landing Page'] || '');
  html += `</table>`;

  // 3. OFFER
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">OFFER</p>`;
  html += `<table>`;
  html += kvRow('Promo', offer['Promo'] || '');
  html += kvRow('Promo Asset', offer['Promo Asset'] || '');
  html += kvRow('Value Callout', offer['Value Callout'] || '');
  html += kvRow('Urgency Element', offer['Urgency Element'] || '');
  html += `</table>`;

  // 4. EDITING INSTRUCTIONS
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">EDITING INSTRUCTIONS</p>`;
  html += `<table>`;
  html += kvRow('Pacing', editing['Pacing'] || '');
  html += kvRow('Resolution', editing['Resolution'] || '');
  html += kvRow('Caption & Graphics', editing['Caption & Graphics'] || editing['Captions'] || '');
  html += kvRow('Transitions', editing['Transitions'] || '');
  html += kvRow('Music', editing['Music'] || '');
  html += kvRow('Voiceover', editing['Voiceover'] || '');
  html += kvRow('Asset', editing['Asset'] || '');
  html += kvRow('Notes', editing['Notes'] || '');
  html += `</table>`;

  // 5. REFERENCE (if present)
  const reference = parseKvTable(markdownContent, 'REFERENCE');
  if (Object.keys(reference).length > 0) {
    html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">REFERENCE</p>`;
    html += `<table>`;
    for (const [k, v] of Object.entries(reference)) {
      html += kvRow(k, v);
    }
    html += `</table>`;
  }

  // 6. SCRIPT (HOOKS) — uses the defensive normalizer to handle any LLM
  //    column-shape drift (UGC-shaped tables landing in an Ecom render etc.)
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">SCRIPT (HOOKS)</p>`;
  html += `<table>`;
  html += `<tr><th style="${scriptHeaderStyle}width:40px;">LINE #</th><th style="${scriptHeaderStyle}width:100px;">SHOT TYPE</th><th style="${scriptHeaderStyle}width:220px;">SUGGESTED VISUAL</th><th style="${scriptHeaderStyle}">HOOK LINE</th></tr>`;
  let ecomHookDrift = false;
  let ecomHookRowsRendered = 0;
  hooks.forEach((row, i) => {
    const r = normalizeBodyRow(row, i, 'ecom4');
    if (!r) return; // skip leaked headers / blank rows
    if (r.driftDetected) ecomHookDrift = true;
    ecomHookRowsRendered++;
    html += `<tr><td style="${scriptCellStyle}text-align:center;width:40px;">${esc(r.num)}</td><td style="${scriptCellStyle}width:100px;">${esc(r.shotType)}</td><td style="${scriptCellStyle}width:220px;">${esc(r.visual)}</td><td style="${scriptCellStyle}">${esc(r.line)}</td></tr>`;
  });
  if (ecomHookRowsRendered === 0) {
    html += `<tr><td colspan="4" style="${scriptCellStyle}text-align:center;color:#999;">No hooks parsed</td></tr>`;
  }
  html += `</table>`;
  if (ecomHookDrift) {
    console.warn('[downloadEcomBriefDoc] Hook table column drift detected and auto-corrected during render. The LLM produced a non-Ecom column shape.');
  }

  // 7. SCRIPT (BODY) — same defensive treatment as the hooks table
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">SCRIPT (BODY)</p>`;
  html += `<table>`;
  html += `<tr><th style="${scriptHeaderStyle}width:40px;">LINE #</th><th style="${scriptHeaderStyle}width:100px;">SHOT TYPE</th><th style="${scriptHeaderStyle}width:220px;">SUGGESTED VISUAL</th><th style="${scriptHeaderStyle}">SCRIPT LINE</th></tr>`;
  let ecomBodyDrift = false;
  let ecomBodyRowsRendered = 0;
  body.forEach((row, i) => {
    const r = normalizeBodyRow(row, i, 'ecom4');
    if (!r) return;
    if (r.driftDetected) ecomBodyDrift = true;
    ecomBodyRowsRendered++;
    html += `<tr><td style="${scriptCellStyle}text-align:center;width:40px;">${esc(r.num)}</td><td style="${scriptCellStyle}width:100px;">${esc(r.shotType)}</td><td style="${scriptCellStyle}width:220px;">${esc(r.visual)}</td><td style="${scriptCellStyle}">${esc(r.line)}</td></tr>`;
  });
  if (ecomBodyRowsRendered === 0) {
    html += `<tr><td colspan="4" style="${scriptCellStyle}text-align:center;color:#999;">No body rows parsed</td></tr>`;
  }
  html += `</table>`;
  if (ecomBodyDrift) {
    console.warn('[downloadEcomBriefDoc] Body table column drift detected and auto-corrected during render. Original markdown had a non-Ecom column shape; the SCRIPT LINE column was reconstructed from the right-most content cell.');
  }

  html += `<p style="margin-top:30px;font-size:9pt;color:#999;border-top:1px solid #ddd;padding-top:8px;font-family:Arial,sans-serif;">Generated by Viasox Marketing Intelligence</p>`;
  html += `</body></html>`;

  const blob = new Blob([html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  // Strip only OS-illegal chars; preserve casing, hyphens, and underscores so
  // the file name matches the Asana task ID exactly (e.g., "SOX-374_ES.doc").
  const safeBriefId = briefId.replace(/[\\/:*?"<>|]/g, '_');
  a.download = `${safeBriefId}.doc`;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Download content as PDF using a print-to-PDF approach
 */
export function downloadAsPdf(content: string, title: string): void {
  const html = buildHtmlDocument(content, title);
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    // Fallback: if popup blocked, download as HTML with .pdf suggestion
    alert('Pop-up blocked. Please allow pop-ups to generate PDF, or use the .doc download option.');
    return;
  }
  printWindow.document.write(html);
  printWindow.document.close();

  // Use a flag to prevent double print() invocation
  let printed = false;
  const triggerPrint = () => {
    if (printed) return;
    printed = true;
    printWindow.print();
  };

  // Wait for content to render, then trigger print (Save as PDF)
  printWindow.onload = triggerPrint;
  // Fallback for browsers where onload doesn't fire on document.write
  setTimeout(triggerPrint, 500);
}

// ─── Router: pick the right exporter for an ad type ─────────────────────

import type { AdType } from '../engine/types';

export function downloadBriefForAdType(
  adType: AdType,
  markdown: string,
  product: string,
  taskName: string,
): void {
  // Three delivery paths, three downloaders:
  //   - Production (Nora films with crew + hired actors) → AGC CSV
  //   - Creator (regular person filming on phone, often older / non-tech) → UGC Doc
  //   - Editing (existing footage / AI generation) → Ecom Doc
  //   - Static → Ecom Doc (single-image, uses the doc shape)
  switch (adType) {
    // Production path → AGC CSV
    case 'AGC (Actor Generated Content)':
    case 'Founder Style':
    case 'Spokesperson':
    case 'Fake Podcast Ads':
    case 'Packaging/Employee':
      downloadProductionBriefCsv(markdown, product, adType, taskName);
      return;

    // Creator path → UGC Doc (simplified, 3-col body, 5 hooks)
    case 'UGC (User Generated Content)':
      downloadUgcBriefDoc(markdown, taskName);
      return;

    // AI-generation path → Full AI Doc (Visual + Voiceover, no Shot Type)
    case 'Full AI (Documentary, story, education, etc)':
      downloadFullAiBriefDoc(markdown, taskName);
      return;

    // Editing path → Ecom Doc
    case 'Ecom Style':
    case 'AI Podcast':
    case 'Static':
    default:
      downloadEcomBriefDoc(markdown, taskName);
      return;
  }
}

// ─── Full AI Brief — DOC (Visual + Voiceover, no Shot Type column) ──────
//
// Full AI ads are 100% AI-generated, so the Ecom template's Shot Type
// column (built around real footage tags like "Talking Head") doesn't
// apply. Repeated observation showed the model would dump scene
// descriptions into both the Visual AND the Script Line columns,
// leaving the brief with no actual voiceover.
//
// This exporter renders the simplified Full AI table shape: just a
// row number, the visual prompt for the AI generator, and the
// voiceover line that will be spoken. The "Voiceover" header is
// chosen deliberately (vs "Script Line") because it can only mean
// audio, removing any ambiguity.
//
// Reuses the same styling as the Ecom DOC (navy section labels,
// Arial, light-gray borders) so it's visually consistent with the
// other DOC outputs.
export function downloadFullAiBriefDoc(markdownContent: string, overrideBriefId?: string): void {
  const esc = escapeHtml;

  const briefInfo = parseKvTable(markdownContent, 'BRIEF INFO');
  const strategy = parseKvTable(markdownContent, 'STRATEGY');
  const offer = parseKvTable(markdownContent, 'OFFER');
  const editing = parseKvTable(markdownContent, 'EDITING INSTRUCTIONS');
  const hooks = parseScriptTable(markdownContent, 'SCRIPT \\(HOOKS\\)');
  const body = parseScriptTable(markdownContent, 'SCRIPT \\(BODY\\)');

  const briefId = overrideBriefId || briefInfo['Brief ID'] || 'FULLAI_BRIEF';

  // Reuse Ecom DOC styling for visual consistency across all DOC outputs.
  const NAVY = '#1b365d';
  const BORDER = '#bfbfbf';
  const sectionHeaderStyle = `padding:6px 10px;font-weight:bold;font-size:12pt;color:#000;font-family:Arial,sans-serif;`;
  const labelCellStyle = `background:${NAVY};padding:6px 10px;font-weight:bold;font-size:10pt;color:#ffffff;border:1px solid ${BORDER};width:160px;vertical-align:top;font-family:Arial,sans-serif;`;
  const valueCellStyle = `padding:6px 10px;font-size:10pt;color:#000;border:1px solid ${BORDER};vertical-align:top;font-family:Arial,sans-serif;`;
  const scriptHeaderStyle = `background:${NAVY};padding:6px 10px;font-weight:bold;font-size:10pt;color:#ffffff;border:1px solid ${BORDER};text-align:left;font-family:Arial,sans-serif;`;
  const scriptCellStyle = `padding:6px 10px;font-size:10pt;color:#000;border:1px solid ${BORDER};vertical-align:top;font-family:Arial,sans-serif;`;

  const kvRow = (label: string, value: string) =>
    `<tr><td style="${labelCellStyle}">${esc(label)}</td><td style="${valueCellStyle}">${esc(value || '—')}</td></tr>`;

  let html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(briefId)}</title>
<style>
@page { margin: 0.75in; }
body { font-family: Arial, sans-serif; max-width: 850px; margin: 0 auto; padding: 30px; color: #000; font-size: 11pt; }
table { border-collapse: collapse; width: 100%; margin-bottom: 16px; page-break-inside: avoid; }
h1 { text-align: center; }
</style></head><body>`;

  html += `<h1 style="font-size:16pt;color:#000;margin:0 0 20px 0;font-weight:bold;font-family:Arial,sans-serif;">Full AI Brief</h1>`;

  // 1. BRIEF INFO
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">BRIEF INFO</p>`;
  html += `<table>`;
  html += kvRow('Brief ID', briefId);
  html += kvRow('Date', briefInfo['Date'] || '');
  html += kvRow('Product', briefInfo['Product'] || '');
  html += kvRow('Collection', briefInfo['Collection'] || '');
  html += kvRow('Collection Asset', briefInfo['Collection Asset'] || '');
  html += kvRow('Format', briefInfo['Format'] || '');
  html += `</table>`;

  // 2. STRATEGY
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">STRATEGY</p>`;
  html += `<table>`;
  html += kvRow('Awareness Level', strategy['Awareness Level'] || '');
  html += kvRow('Primary Emotion', strategy['Primary Emotion'] || '');
  html += kvRow('Avatar', strategy['Avatar'] || '');
  html += kvRow('Landing Page', strategy['Landing Page'] || '');
  html += `</table>`;

  // 3. OFFER
  if (Object.keys(offer).length > 0) {
    html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">OFFER</p>`;
    html += `<table>`;
    html += kvRow('Promo', offer['Promo'] || '');
    html += kvRow('Promo Asset', offer['Promo Asset'] || '');
    html += kvRow('Value Callout', offer['Value Callout'] || '');
    html += kvRow('Urgency Element', offer['Urgency Element'] || '');
    html += `</table>`;
  }

  // 4. EDITING INSTRUCTIONS
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">EDITING INSTRUCTIONS</p>`;
  html += `<table>`;
  html += kvRow('Pacing', editing['Pacing'] || '');
  html += kvRow('Resolution', editing['Resolution'] || '');
  html += kvRow('Caption & Graphics', editing['Caption & Graphics'] || editing['Captions'] || '');
  html += kvRow('Transitions', editing['Transitions'] || '');
  html += kvRow('Music', editing['Music'] || '');
  html += kvRow('Voiceover', editing['Voiceover'] || '');
  html += kvRow('Asset', editing['Asset'] || '');
  html += kvRow('Notes', editing['Notes'] || '');
  html += `</table>`;

  // Full AI rows go through the shared right-anchored normalizer. The
  // voiceover (= the spoken line) is always the rightmost cell; the visual
  // is second-to-last. Any Shot Type / Building Block column the model
  // added sits in the middle and is dropped — Full AI has no Shot Type
  // column. This is the same logic the Ecom + UGC exporters use, so the
  // drift behavior is identical across every template.
  const normalizeRow = (row: string[], i: number): { num: string; visual: string; voiceover: string } => {
    const r = normalizeBodyRow(row, i, 'ecom4');
    if (!r) return { num: '', visual: '', voiceover: '' };
    return { num: r.num, visual: r.visual, voiceover: r.line };
  };

  // 5. SCRIPT (HOOKS)
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">SCRIPT (HOOKS)</p>`;
  html += `<table>`;
  html += `<tr>` +
    `<th style="${scriptHeaderStyle}width:40px;">#</th>` +
    `<th style="${scriptHeaderStyle}">SUGGESTED VISUAL</th>` +
    `<th style="${scriptHeaderStyle}">VOICEOVER</th>` +
    `</tr>`;
  hooks.forEach((row, i) => {
    const { num, visual, voiceover } = normalizeRow(row, i);
    html += `<tr>` +
      `<td style="${scriptCellStyle}text-align:center;width:40px;">${esc(num)}</td>` +
      `<td style="${scriptCellStyle}">${esc(visual)}</td>` +
      `<td style="${scriptCellStyle}">${esc(voiceover)}</td>` +
      `</tr>`;
  });
  if (hooks.length === 0) {
    html += `<tr><td colspan="3" style="${scriptCellStyle}text-align:center;color:#999;">No hooks parsed</td></tr>`;
  }
  html += `</table>`;

  // 6. SCRIPT (BODY)
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">SCRIPT (BODY)</p>`;
  html += `<table>`;
  html += `<tr>` +
    `<th style="${scriptHeaderStyle}width:40px;">#</th>` +
    `<th style="${scriptHeaderStyle}">SUGGESTED VISUAL</th>` +
    `<th style="${scriptHeaderStyle}">VOICEOVER</th>` +
    `</tr>`;
  body.forEach((row, i) => {
    const { num, visual, voiceover } = normalizeRow(row, i);
    html += `<tr>` +
      `<td style="${scriptCellStyle}text-align:center;width:40px;">${esc(num)}</td>` +
      `<td style="${scriptCellStyle}">${esc(visual)}</td>` +
      `<td style="${scriptCellStyle}">${esc(voiceover)}</td>` +
      `</tr>`;
  });
  if (body.length === 0) {
    html += `<tr><td colspan="3" style="${scriptCellStyle}text-align:center;color:#999;">No body rows parsed</td></tr>`;
  }
  html += `</table>`;

  html += `<p style="margin-top:30px;font-size:9pt;color:#999;border-top:1px solid #ddd;padding-top:8px;font-family:Arial,sans-serif;">Generated by Viasox Marketing Intelligence</p>`;
  html += `</body></html>`;

  const blob = new Blob([html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const safeBriefId = briefId.replace(/[\\/:*?"<>|]/g, '_');
  a.download = `${safeBriefId}_FULLAI.doc`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── UGC Creator Brief — DOC (5 hooks, 3-col body) ──────────────────────
//
// Reuses the Ecom DOC styling (navy headers, Arial, light-gray table
// borders) so it feels visually consistent with the other doc briefs. The
// content is dramatically simpler: only the sections a non-technical
// creator needs to film their video.
//
// Markdown sections expected from the LLM (per buildUgcTemplate in
// briefTemplates.ts):
//   - BRIEF INFO       — KV table (Brief ID, Date, Product, Angle,
//                        Persona, Length, Talent, Location)
//   - STRATEGY         — KV table (Awareness, Primary Emotion, Avatar)
//   - VOICE & TONE     — prose paragraph (no table)
//   - SCRIPT (HOOKS)   — 4-col table: # | Hook Style | Visual | Line
//   - SCRIPT (BODY)    — 3-col table: Shot Visuals | Shot Type | Lines
export function downloadUgcBriefDoc(markdownContent: string, overrideBriefId?: string): void {
  const esc = escapeHtml;

  const briefInfo = parseKvTable(markdownContent, 'BRIEF INFO');
  const strategy = parseKvTable(markdownContent, 'STRATEGY');
  const voiceToneSection = extractProseSection(markdownContent, 'VOICE & TONE');
  const hooks = parseScriptTable(markdownContent, 'SCRIPT \\(HOOKS\\)');
  const body = parseScriptTable(markdownContent, 'SCRIPT \\(BODY\\)');

  const briefId = overrideBriefId || briefInfo['Brief ID'] || 'UGC_BRIEF';

  // Reuse the Ecom DOC's visual language so the doc style stays consistent
  // across brief types — just lighter content inside.
  const NAVY = '#1b365d';
  const BORDER = '#bfbfbf';
  const sectionHeaderStyle = `padding:6px 10px;font-weight:bold;font-size:12pt;color:#000;font-family:Arial,sans-serif;`;
  const labelCellStyle = `background:${NAVY};padding:6px 10px;font-weight:bold;font-size:10pt;color:#ffffff;border:1px solid ${BORDER};width:160px;vertical-align:top;font-family:Arial,sans-serif;`;
  const valueCellStyle = `padding:6px 10px;font-size:10pt;color:#000;border:1px solid ${BORDER};vertical-align:top;font-family:Arial,sans-serif;`;
  const scriptHeaderStyle = `background:${NAVY};padding:6px 10px;font-weight:bold;font-size:10pt;color:#ffffff;border:1px solid ${BORDER};text-align:left;font-family:Arial,sans-serif;`;
  const scriptCellStyle = `padding:6px 10px;font-size:10pt;color:#000;border:1px solid ${BORDER};vertical-align:top;font-family:Arial,sans-serif;`;

  const kvRow = (label: string, value: string) =>
    `<tr><td style="${labelCellStyle}">${esc(label)}</td><td style="${valueCellStyle}">${esc(value || '—')}</td></tr>`;

  let html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(briefId)}</title>
<style>
@page { margin: 0.75in; }
body { font-family: Arial, sans-serif; max-width: 850px; margin: 0 auto; padding: 30px; color: #000; font-size: 11pt; }
table { border-collapse: collapse; width: 100%; margin-bottom: 16px; page-break-inside: avoid; }
h1 { text-align: center; }
.voice-tone { padding:10px 14px;border:1px solid ${BORDER};font-size:10.5pt;color:#000;line-height:1.5;background:#f8f9fb;font-family:Arial,sans-serif;margin-bottom:16px;white-space:pre-wrap; }
</style></head><body>`;

  // Title
  html += `<h1 style="font-size:16pt;color:#000;margin:0 0 20px 0;font-weight:bold;font-family:Arial,sans-serif;">UGC Creator Brief</h1>`;

  // 1. BRIEF INFO — UGC-specific fields
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">BRIEF INFO</p>`;
  html += `<table>`;
  html += kvRow('Brief ID', briefId);
  html += kvRow('Date', briefInfo['Date'] || '');
  html += kvRow('Product', briefInfo['Product'] || '');
  html += kvRow('Angle', briefInfo['Angle'] || '');
  html += kvRow('Persona', briefInfo['Persona'] || '');
  html += kvRow('Length', briefInfo['Length'] || briefInfo['Format'] || '');
  html += kvRow('Talent', briefInfo['Talent'] || '');
  html += kvRow('Location', briefInfo['Location'] || '');
  html += `</table>`;

  // 2. STRATEGY — minimal: awareness, emotion, avatar
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">STRATEGY</p>`;
  html += `<table>`;
  html += kvRow('Awareness Level', strategy['Awareness Level'] || '');
  html += kvRow('Primary Emotion', strategy['Primary Emotion'] || '');
  html += kvRow('Avatar', strategy['Avatar'] || '');
  html += `</table>`;

  // 3. VOICE & TONE — prose paragraph, not a table
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">VOICE &amp; TONE</p>`;
  html += `<div class="voice-tone">${esc(voiceToneSection || '—')}</div>`;

  // 4. SCRIPT (HOOKS) — 4 cols: # | Hook Style | Suggested Visual | Hook Line
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">SCRIPT (HOOKS) — 5 Variations</p>`;
  html += `<table>`;
  html += `<tr>` +
    `<th style="${scriptHeaderStyle}width:40px;">#</th>` +
    `<th style="${scriptHeaderStyle}width:140px;">HOOK STYLE</th>` +
    `<th style="${scriptHeaderStyle}width:220px;">SUGGESTED VISUAL</th>` +
    `<th style="${scriptHeaderStyle}">HOOK LINE</th>` +
    `</tr>`;
  hooks.forEach((row) => {
    const [num, style, visual, line] = [row[0] || '', row[1] || '', row[2] || '', row[3] || ''];
    html += `<tr>` +
      `<td style="${scriptCellStyle}text-align:center;width:40px;">${esc(num)}</td>` +
      `<td style="${scriptCellStyle}width:140px;">${esc(style)}</td>` +
      `<td style="${scriptCellStyle}width:220px;">${esc(visual)}</td>` +
      `<td style="${scriptCellStyle}">${esc(line)}</td>` +
      `</tr>`;
  });
  if (hooks.length === 0) {
    html += `<tr><td colspan="4" style="${scriptCellStyle}text-align:center;color:#999;">No hooks parsed</td></tr>`;
  }
  html += `</table>`;

  // 5. SCRIPT (BODY) — 3 cols ONLY: Shot Visuals | Shot Type | Lines
  // Uses the shared defensive normalizer so column-shape drift from the
  // LLM (extra leading number, header-name leak into data, etc.) doesn't
  // produce a doc with empty Lines cells.
  html += `<p style="${sectionHeaderStyle}margin:16px 0 4px 0;">SCRIPT (BODY)</p>`;
  html += `<table>`;
  html += `<tr>` +
    `<th style="${scriptHeaderStyle}">SHOT VISUALS</th>` +
    `<th style="${scriptHeaderStyle}width:140px;">SHOT TYPE</th>` +
    `<th style="${scriptHeaderStyle}">LINES</th>` +
    `</tr>`;
  let ugcBodyDrift = false;
  let ugcBodyRowsRendered = 0;
  body.forEach((row, i) => {
    const r = normalizeBodyRow(row, i, 'ugc3');
    if (!r) return; // skip leaked-header / blank rows
    if (r.driftDetected) ugcBodyDrift = true;
    ugcBodyRowsRendered++;
    html += `<tr>` +
      `<td style="${scriptCellStyle}">${esc(r.visual)}</td>` +
      `<td style="${scriptCellStyle}width:140px;">${esc(r.shotType)}</td>` +
      `<td style="${scriptCellStyle}">${esc(r.line)}</td>` +
      `</tr>`;
  });
  if (ugcBodyRowsRendered === 0) {
    html += `<tr><td colspan="3" style="${scriptCellStyle}text-align:center;color:#999;">No body rows parsed</td></tr>`;
  }
  html += `</table>`;
  if (ugcBodyDrift) {
    console.warn('[downloadUgcBriefDoc] Body table column drift detected and auto-corrected during render.');
  }

  html += `<p style="margin-top:30px;font-size:9pt;color:#999;border-top:1px solid #ddd;padding-top:8px;font-family:Arial,sans-serif;">Generated by Viasox Marketing Intelligence</p>`;
  html += `</body></html>`;

  const blob = new Blob([html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const safeBriefId = briefId.replace(/[\\/:*?"<>|]/g, '_');
  a.download = `${safeBriefId}_UGC.doc`;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Extract a prose section (no table) from markdown by its header. Returns
 * everything between the section header and the next `###`/`##` header,
 * with leading/trailing whitespace trimmed. Used for VOICE & TONE which is
 * a paragraph, not a table.
 */
function extractProseSection(markdown: string, sectionHeader: string): string {
  const headerPattern = new RegExp(`^#{1,4}\\s*[0-9]*\\.?\\s*${sectionHeader.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/&/g, '&amp;|&')}\\s*$`, 'mi');
  const match = headerPattern.exec(markdown);
  if (!match) return '';
  const startIdx = match.index + match[0].length;
  const after = markdown.slice(startIdx);
  // Find the next header (### or ##) to mark the end of this section.
  const nextHeader = /^#{1,4}\s+/m.exec(after);
  const sectionBody = nextHeader ? after.slice(0, nextHeader.index) : after;
  return sectionBody.trim();
}
