import { useState } from 'react';
import type { AutopilotState } from '../../engine/autopilotTypes';
import TaskBriefCard from './TaskBriefCard';
import { downloadEcomBriefDoc } from '../../utils/downloadUtils';
import { addFeedback } from '../../autopilot/memoryStore';

interface Props {
  state: AutopilotState;
  onReset: () => void;
  onRedoTask?: (taskIndex: number, feedback: string) => void;
  redoingIndex?: number | null;
}

export default function BatchResultsView({ state, onReset, onRedoTask, redoingIndex }: Props) {
  const [reviewExpanded, setReviewExpanded] = useState(false);
  const [briefingExpanded, setBriefingExpanded] = useState(false);
  const [feedbackText, setFeedbackText] = useState('');
  const [feedbackSaved, setFeedbackSaved] = useState(false);

  const completed = state.tasks.filter((t) => t.step === 'complete');
  const failed = state.tasks.filter((t) => t.step === 'error');

  const handleExportAll = () => {
    completed.forEach((ts) => {
      if (ts.scriptResult) {
        downloadEcomBriefDoc(ts.scriptResult, ts.task.parsed.name);
      }
    });
  };

  const handleSaveFeedback = () => {
    if (!feedbackText.trim()) return;
    addFeedback({
      date: new Date().toISOString().split('T')[0],
      batchId: new Date().toISOString(),
      source: 'manual_feedback',
      content: feedbackText.trim(),
      context: `Batch with ${state.tasks.length} tasks: ${state.tasks.map((t) => t.task.parsed.name).join(', ')}`,
    });
    setFeedbackSaved(true);
  };

  return (
    <div className="space-y-5">
      {/* Summary */}
      <div className="bg-white rounded-xl border border-slate-200 p-5">
        <div className="flex items-center justify-between mb-3">
          <h3 className="text-lg font-bold text-slate-800">Batch Complete</h3>
          <button
            onClick={onReset}
            className="text-sm text-slate-500 hover:text-slate-700 underline"
          >
            Start New Batch
          </button>
        </div>

        <div className="grid grid-cols-3 gap-3 mb-4">
          <div className="bg-emerald-50 rounded-lg p-3 text-center">
            <div className="text-2xl font-bold text-emerald-700">{completed.length}</div>
            <div className="text-xs text-emerald-600">Briefs Generated</div>
          </div>
          <div className="bg-red-50 rounded-lg p-3 text-center">
            <div className="text-2xl font-bold text-red-700">{failed.length}</div>
            <div className="text-xs text-red-600">Failed</div>
          </div>
          <div className="bg-blue-50 rounded-lg p-3 text-center">
            <div className="text-2xl font-bold text-blue-700">{state.tasks.length}</div>
            <div className="text-xs text-blue-600">Total Tasks</div>
          </div>
        </div>

        {completed.length > 0 && (
          <button
            onClick={handleExportAll}
            className="w-full py-2.5 bg-slate-800 text-white rounded-lg text-sm font-medium hover:bg-slate-900 transition-colors"
          >
            Download All Briefs (.doc) — {completed.length} file{completed.length !== 1 ? 's' : ''}
          </button>
        )}
      </div>

      {/* Creative Intelligence Used */}
      {state.memoryBriefing && (
        <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
          <button
            onClick={() => setBriefingExpanded(!briefingExpanded)}
            className="w-full p-4 flex items-center justify-between text-left hover:bg-slate-50"
          >
            <div className="flex items-center gap-2">
              <span className="text-lg">{'\uD83E\uDDE0'}</span>
              <span className="text-sm font-semibold text-slate-700">Creative Intelligence Used</span>
              <span className="text-[10px] bg-blue-100 text-blue-700 px-2 py-0.5 rounded-full">Memory Active</span>
            </div>
            <span className="text-xs text-slate-400">{briefingExpanded ? 'Collapse' : 'Expand'}</span>
          </button>
          {briefingExpanded && (
            <div className="border-t border-slate-100 p-5">
              <p className="text-[10px] text-slate-400 mb-2">
                This briefing was generated by the Memory Curator and injected into all agents (concept generator, selector, script writer, and reviewer) for this batch.
              </p>
              <pre className="whitespace-pre-wrap text-xs leading-relaxed text-slate-700 font-sans bg-blue-50 rounded-lg p-4">
                {state.memoryBriefing}
              </pre>
            </div>
          )}
        </div>
      )}

      {/* Batch Review */}
      {state.reviewResult && (
        <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
          <button
            onClick={() => setReviewExpanded(!reviewExpanded)}
            className="w-full p-4 flex items-center justify-between text-left hover:bg-slate-50"
          >
            <div className="flex items-center gap-2">
              <span className="text-lg">{'\uD83D\uDD0D'}</span>
              <span className="text-sm font-semibold text-slate-700">QC Review Report</span>
            </div>
            <span className="text-xs text-slate-400">{reviewExpanded ? 'Collapse' : 'Expand'}</span>
          </button>
          {reviewExpanded && (
            <div className="border-t border-slate-100 p-5">
              <pre className="whitespace-pre-wrap text-xs leading-relaxed text-slate-700 font-sans">
                {state.reviewResult}
              </pre>
            </div>
          )}
        </div>
      )}

      {/* Individual Brief Cards */}
      <div className="space-y-3">
        {state.tasks.map((ts, i) => (
          <TaskBriefCard
            key={i}
            taskState={ts}
            index={i}
            onRedo={onRedoTask}
            isRedoing={redoingIndex === i}
          />
        ))}
      </div>

      {/* Download All (bottom) */}
      {completed.length > 0 && (
        <div className="bg-white rounded-xl border border-slate-200 p-5">
          <button
            onClick={handleExportAll}
            className="w-full py-3 bg-slate-800 text-white rounded-lg text-sm font-medium hover:bg-slate-900 transition-colors flex items-center justify-center gap-2"
          >
            <span>{'\uD83D\uDCE5'}</span>
            Download All Briefs (.doc) — {completed.length} file{completed.length !== 1 ? 's' : ''}
          </button>
        </div>
      )}

      {/* Post-Batch Feedback */}
      <div className="bg-white rounded-xl border border-slate-200 p-5">
        <h4 className="text-sm font-semibold text-slate-700 mb-2">
          Post-Batch Feedback <span className="text-slate-400 font-normal">(optional)</span>
        </h4>
        <p className="text-xs text-slate-400 mb-3">
          What worked? What didn't? What should change next time? This feedback is saved to the creative memory and will influence future batches.
        </p>
        {feedbackSaved ? (
          <div className="bg-emerald-50 rounded-lg p-3 text-xs text-emerald-700 flex items-center gap-2">
            <span>{'\u2713'}</span> Feedback saved to creative memory. It will influence future batches.
          </div>
        ) : (
          <>
            <textarea
              value={feedbackText}
              onChange={(e) => setFeedbackText(e.target.value)}
              placeholder="e.g., 'The neuropathy briefs were strong but swelling briefs felt too generic. Lean more into storytelling next time. Hooks were too similar — need more variety between question and statement hooks.'"
              className="w-full border border-slate-200 rounded-lg p-3 text-xs text-slate-700 resize-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              rows={3}
            />
            <button
              onClick={handleSaveFeedback}
              disabled={!feedbackText.trim()}
              className="mt-2 text-xs bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
            >
              Save Feedback to Memory
            </button>
          </>
        )}
      </div>
    </div>
  );
}
