/**
 * Review Analysis Data Loader
 *
 * Loads the pre-processed review analysis JSON that was generated by
 * scripts/preprocess-reviews.mjs from the raw review CSVs.
 *
 * The JSON is imported statically at build time — no runtime CSV upload needed.
 * The data is identical to what the in-browser analysis pipeline produces.
 */

import reviewData from './reviewAnalysis.json';
import type { FullAnalysis } from '../engine/types';

// The JSON has an extra _meta field from the preprocessor — strip it for type safety
const { _meta: _, ...analysisData } = reviewData as Record<string, unknown>;

/**
 * The embedded review analysis, pre-computed from 110K+ reviews.
 * Same structure as the runtime `runFullAnalysis()` output.
 */
export const embeddedReviewAnalysis: FullAnalysis = analysisData as unknown as FullAnalysis;

/**
 * Check if embedded review analysis data is available.
 */
export function hasEmbeddedReviews(): boolean {
  return embeddedReviewAnalysis?.totalReviews > 0;
}
