/**
 * Sales Enrichment Data Loader
 *
 * Loads the pre-processed sales enrichment JSON that was generated by
 * scripts/preprocess-sales-data.mjs from the raw orders, customers, and reviews CSVs.
 *
 * The JSON is imported statically at build time — no runtime file upload needed.
 */

import salesData from './salesEnrichment.json';

// ─── Types ───────────────────────────────────────────────────────────────────

export interface SalesQuote {
  text: string;
  rating: number;
  product: string;
  verified: boolean;
}

export interface PatternEntry {
  name: string;
  count: number;
  pct: number;
}

export interface SegmentProductData {
  reviewCount: number;
  reviewPct: number;
  revenue?: number;
}

export interface CrossPurchaseCombo {
  combo: string;
  customers: number;
  pct: number;
}

export interface ProductLinePenetration {
  category: string;
  customers: number;
  pct: number;
}

export interface GeoEntry {
  country: string;
  customers: number;
  pct: number;
  revenue: number;
}

export interface RegionEntry {
  region: string;
  customers: number;
  pct: number;
  revenue: number;
}

export interface SegmentSales {
  linkedReviewers: number;
  linkRate: number;
  totalRevenue: number;
  totalGrossRevenue: number;
  totalOrderLines: number;
  uniqueCustomers: number;
  avgLifetimeValue: number;
  avgOrderLines: number;
  avgOrderValue: number;
  repeatPurchaseRate: number;
  repeatBuyers: number;
  crossPurchase: {
    boughtMultipleLines: number;
    pctBoughtMultiple: number;
    productLinePenetration: ProductLinePenetration[];
    combos: CrossPurchaseCombo[];
  };
  discountUsage: {
    usedDiscount: number;
    pctUsedDiscount: number;
  };
  geography: GeoEntry[];
  topRegions: RegionEntry[];
}

export interface EnrichedSegment {
  layer: 'identity' | 'motivation';
  reviewCount: number;
  reviewPct: number;
  avgRating: number;
  fiveStarPct: number;
  byProduct: Record<string, SegmentProductData>;
  topPains: PatternEntry[];
  topBenefits: PatternEntry[];
  topTransformations: PatternEntry[];
  quotes: SalesQuote[];
  sales: SegmentSales;
}

export interface EnrichedOverlap {
  identity: string;
  motivation: string;
  reviewCount: number;
  percentOfIdentity: number;
  percentOfMotivation: number;
  avgRating: number;
  byProduct: Record<string, { count: number; pct: number }>;
  sales: {
    linkedReviewers: number;
    totalRevenue: number;
    totalOrderLines: number;
    avgLifetimeValue: number;
    avgOrders: number;
    repeatPurchaseRate: number;
    crossPurchaseRate: number;
  };
}

export interface ProductAffinityEntry {
  segmentName: string;
  layer: string;
  reviewCount: number;
  shareOfProduct: number;
  concentrationIndex: number;
  revenue: number;
  revenueShare: number;
}

export interface CrossPurchaseMatrix {
  totalCustomers: number;
  productOwnership: Record<string, { customers: number; pct: number }>;
  combos: Array<{
    combo: string;
    customers: number;
    pctOfTotal: number;
    avgCombinedSpend: number;
  }>;
}

export interface CustomerJourney {
  emailHint: string;
  totalSpend: number;
  orderLines: number;
  productsOwned: string[];
  firstOrder: string;
  lastOrder: string;
  location: string | null;
  sampleQuote: string | null;
  reviewCount: number;
  reviewProducts: string[];
}

export interface SalesEnrichmentMeta {
  generatedAt: string;
  totalReviews: number;
  totalOrderLines: number;
  totalRevenue: number;
  totalCustomersInOrders: number;
  uniqueReviewerEmails: number;
  reviewersLinkedToOrders: number;
  linkRate: number;
}

export interface SalesEnrichmentData {
  meta: SalesEnrichmentMeta;
  segments: Record<string, EnrichedSegment>;
  segmentMeta: {
    totalReviews: number;
    unsegmented: { count: number; pct: number };
    multiSegment: { count: number; pct: number };
  };
  crossSegmentOverlaps: EnrichedOverlap[];
  productAffinity: Record<string, ProductAffinityEntry[]>;
  crossPurchaseMatrix: CrossPurchaseMatrix;
  customerJourneys: Record<string, CustomerJourney[]>;
}

// ─── Exported data ───────────────────────────────────────────────────────────

export const salesEnrichment: SalesEnrichmentData = salesData as unknown as SalesEnrichmentData;

/**
 * Look up a segment by display name (case-insensitive).
 * Handles both "Comfort Seeker" and "comfort seeker" lookups.
 */
export function getEnrichedSegment(displayName: string): EnrichedSegment | undefined {
  const key = displayName.toLowerCase();
  return salesEnrichment.segments[key];
}

/**
 * Check if sales enrichment data is available (i.e., the JSON was generated).
 */
export function hasSalesEnrichment(): boolean {
  return salesEnrichment?.meta?.totalRevenue > 0;
}
