/**
 * Brief Templates — only TWO templates, mirroring the historic Viasox
 * delivery structure.
 *
 *   • AGC template (CSV) — every PRODUCTION brief. AGC, Founder Style,
 *     Spokesperson, Filmed Podcast (Fake Podcast Ads), Packaging/Employee,
 *     UGC. Same 9-hook matrix, same 10-column shot table, same Building
 *     Block rules — the AD-TYPE NUANCE block injects the per-format
 *     flavoring (talent type, setting, body format, etc.).
 *
 *   • Ecom template (Doc) — every EDITING brief. Ecom Style, Full AI
 *     variants, AI Podcast. Same 8-section structure — the AD-TYPE NUANCE
 *     block injects per-format flavoring (AI generation prompts for Full
 *     AI, dialogue + avatar specs for AI Podcast, footage library tags
 *     for Ecom Style).
 *
 * Static keeps its own inline format in scriptPrompt.ts (single-image,
 * fundamentally different from the video brief shape).
 */

import type { ScriptParams } from '../engine/types';

// ─── Template Router ────────────────────────────────────────────────────

export type BriefTemplateId = 'ecom' | 'agc';

/**
 * Map an ad type to its delivery template.
 *   - Production path → 'agc'
 *   - Editing path    → 'ecom'
 */
export function getBriefTemplateId(adType: ScriptParams['adType']): BriefTemplateId {
  switch (adType) {
    // Production — anything Nora films
    case 'AGC (Actor Generated Content)':
    case 'Founder Style':
    case 'Spokesperson':
    case 'Fake Podcast Ads':
    case 'Packaging/Employee':
    case 'UGC (User Generated Content)':
      return 'agc';

    // Editing — anything assembled from footage or generated by AI
    case 'Ecom Style':
    case 'AI Podcast':
    case 'Full AI (Documentary, story, education, etc)':
      return 'ecom';

    default:
      return 'ecom';
  }
}

// ─── Shared helpers ─────────────────────────────────────────────────────

function promoLine(offer: ScriptParams['offer']): string {
  if (offer === 'B2G3') return 'Buy 2 Get 3 Free (5 for $60)';
  if (offer === 'B1G1') return 'Buy 1 Get 1 Free';
  return 'None';
}

function valueCallout(offer: ScriptParams['offer']): string {
  if (offer === 'B2G3') return '5 Pairs for $60 ($12 per pair, $90 worth of free socks)';
  if (offer === 'B1G1') return '2 Pairs for $30';
  return 'None';
}

function productLabel(product: ScriptParams['product']): string {
  if (product === 'EasyStretch') return 'EasyStretch Socks (Non-Binding Diabetic Socks)';
  if (product === 'Compression') return 'Compression Socks (Knee-High)';
  if (product === 'Ankle Compression') return 'Ankle Compression Socks';
  return product;
}

// ─── AD-TYPE NUANCE blocks ──────────────────────────────────────────────
//
// These tell the LLM how to flavor the strategic content for the specific
// ad type, even though the OUTPUT STRUCTURE is the same AGC or Ecom shape.
// Same brief skeleton, different soul.

function agcAdTypeNuance(adType: ScriptParams['adType']): string {
  switch (adType) {
    case 'AGC (Actor Generated Content)':
      return `**AD TYPE: AGC — Hired actor + full crew.**
- Location: cinematic, controlled environment (home interior, outdoor location, studio with set dressing). Specify the world.
- Talent: hired actor in their 30s-60s embodying the target persona. Describe age range, look, energy, wardrobe, personality.
- Body format: ${'agcBodyFormat' in (({} as ScriptParams)) ? 'see agcBodyFormat param' : 'Face-to-Camera OR POV — pick one and stay consistent'}.
- The viewer should NOT realize this is acted. It should feel authentic but look elevated.`;

    case 'Founder Style':
      return `**AD TYPE: Founder Style — The actual Viasox founder (or a stand-in playing the founder) speaks directly to camera.**
- Location: the founder's authentic environment — Viasox warehouse, his office, packing station. The environment IS the proof.
- Talent: a man in his 40s-60s, business-casual, warm authority. NOT polished commercial — authentic founder energy.
- Body format: predominantly ON CAMERA (face-to-camera). VO inserts allowed for B-roll cutaways but the founder's face anchors the ad.
- Voice: personal, passionate, first-person. "Let me tell you why we built this..." energy. NOT a polished script — sounds like a real conversation.
- Opening: dramatic establishing shot of the warehouse (scale and inventory visible), then settle into medium shot on the founder.`;

    case 'Spokesperson':
      return `**AD TYPE: Spokesperson — Credentialed expert (nurse, doctor, podiatrist, healthcare professional) presents the product.**
- Location: clean studio OR an environment that reinforces authority (clinic backdrop, professional desk with credentials visible). NOT the founder's warehouse.
- Talent: credentialed-looking 35-60+ year old. Smart-casual to professional wardrobe. Credentials should be visible or named (scrubs, white coat, name tag, "Registered Nurse, 12+ years bedside").
- Body format: ON CAMERA primary. The expert's face + voice carry credibility.
- Voice: authoritative, evidence-based, warm. NOT salesy. Educator energy — "the most knowledgeable woman in the room who's also the kindest."
- Every claim must be defensible — flag any unverifiable assertion for review.`;

    case 'Fake Podcast Ads':
      return `**AD TYPE: Filmed Podcast — Two real hosts in a podcast set having a scripted conversation that feels organic.**
- Location: podcast set — two chairs, table, podcast mics visible, warm lighting, plants/bookshelves in background.
- Talent: TWO people. Host A = curious questioner / "skeptic" who asks what the viewer is thinking. Host B = the "believer" / experienced user who answers with specifics. Visually distinct from each other (age, wardrobe, vibe).
- Body format: DIALOGUE. Lines column alternates between Host A and Host B. Use the Talent Notes column to indicate which host speaks each line ("HOST A", "HOST B").
- The PRODUCT DISCOVERY MOMENT must feel earned — not a forced ad break. Build curiosity in Host A, then Host B reveals.
- 3 camera angles assumed: two-shot wide, Host A close-up, Host B close-up.`;

    case 'Packaging/Employee':
      return `**AD TYPE: Packaging / Employee — Behind-the-scenes warehouse content with actors playing employees.**
- Location: warehouse zones — picking aisle (shelves of inventory), packing station (table, tape gun, boxes), loading dock (packages stacked). The workplace IS the visual story.
- Talent: 1-3 actors playing employees. Wardrobe = branded apron / casual workwear / shipping uniform. Cast for relatability, NOT glamour.
- Body format: mix of POV/SCRIPT (VO over employee action) and brief ON CAMERA moments. Each row should describe what the employee is physically doing (picking, inspecting, packing, labeling, handing off).
- Use the Shot Notes column to specify the warehouse zone for each shot.
- Voice: warm, industrious, human. NOT corporate. ASMR-adjacent packing rhythm is welcome.`;

    case 'UGC (User Generated Content)':
      return `**AD TYPE: UGC — Raw, phone-shot, native-feeling content from a "real person."**
- Location: real-world environments — the talent's home (couch, kitchen, bathroom), car, office, walking around. NOT a studio.
- Talent: real-person aesthetic — phone-shot framing, natural light, unstaged. Cast a 35-65 year old who looks like a Viasox customer, not an actor.
- Body format: Selfie Talking Head primary. POV Handheld for product demo. Use the Shot Type column for "Selfie Talking Head," "POV Handheld," "Reaction Shot," "Phone Screen Recording," "Mirror Selfie," "Casual B-Roll."
- Voice: conversational, unscripted-feeling. Natural filler words ("honestly," "actually," "just"). The Lines column can include loose phrasing — the talent will ad-lib in production.
- Production target: should look like organic social content. NO crew, NO professional lighting feel.`;

    default:
      return '';
  }
}

function ecomAdTypeNuance(adType: ScriptParams['adType']): string {
  switch (adType) {
    case 'Ecom Style':
      return `**AD TYPE: Ecom Style — Editing brief built from EXISTING Viasox footage + AI voiceover.**
- Shot Type column uses footage tags: Talking Head, Putting On Socks, Feet Up Lifestyle, Bare Legs – Condition, Walking, Standing Feet, Before/After Reveal, Studio Product Shot, Animation / Motion Graphics, Text/Title Card, Socks With Shoes, Documentary / Interview, Product Flat Lay, Branded Shipping Box, EGC / Warehouse, Lifestyle Flat Lay, Material Close-up, PNG Cutout, Home Environment, Outdoor Setting.
- Footage we do NOT have — NEVER imply: indoor gym/fitness, medical offices/clinical settings, sports activities, travel/airports, restaurants, children, pets.
- Suggested Visual column = one conversational sentence (8-20 words) describing what the viewer sees. NOT a tag, NOT vague ("b-roll of feet").
- Voice: real person talking to a friend. Natural filler words. NO copywriter prose.`;

    case 'Full AI (Documentary, story, education, etc)':
      return `**AD TYPE: Full AI — 100% AI-generated visuals via Veo / Sora / Runway. NO real footage.**
- Shot Type column uses AI-generation shot labels: "AI Scene," "AI B-Roll," "AI Close-Up," "AI Wide Establishing," "AI Montage," "Archival-Style AI," "AI Voiceover Over B-Roll," "AI Talking Head," "Text/Title Card."
- DO NOT use the Ecom footage library tags. Full AI is not built from existing footage.
- Suggested Visual column = a paste-ready generation prompt: subject, action, environment, mood, camera language, lighting. Specific enough that an editor pastes it directly into Veo/Sora/Runway.
- Specification: ${params_fullAiSpecification('Documentary')} narrative mode.
- Visual Style: cohesive characters / fully VO / talking-to-camera / no-humans-shown / historical visuals (depending on params).
- Voice: cinematic, documentary VO, educational exposition, or aspirational manifesto — NOT casual Ecom voice.
- Visual Grounding Rules from the Ecom template DO NOT apply. AI can depict any environment.
- If a character recurs across scenes, describe them the same way every time — identity consistency is the editor's challenge.`;

    case 'AI Podcast':
      return `**AD TYPE: AI Podcast — Two AI-generated avatars in conversation. Editing brief — no shoot.**
- Shot Type column uses AI-podcast labels: "AI Two-Shot," "AI Host A Close-Up," "AI Host B Close-Up," "AI Mic Close-Up," "AI Over-the-Shoulder."
- The Suggested Visual column for EACH speaking row must include the avatar profile + the set description as a paste-ready AI prompt. Same avatar description for Host A every time; same for Host B; same set every time. Identity consistency depends on it.
- Lines column = dialogue. Use Talent Notes to indicate which host speaks ("HOST A" / "HOST B"). The PRODUCT DISCOVERY MOMENT must be marked explicitly in the Building Block column when it occurs.
- In the EDITING INSTRUCTIONS section, dedicate the Asset field to: (a) Host A full avatar prompt, (b) Host B full avatar prompt, (c) shared set description — all paste-ready, all reusable across clips.
- Voice: conversational, organic. NOT a salesy ad break. Build curiosity in Host A, reveal in Host B.`;

    default:
      return '';
  }
}

// Tiny helper — only used in the Full AI nuance block to surface specification.
function params_fullAiSpecification(fallback: string): string {
  return `[${fallback} — see params.fullAiSpecification if set]`;
}

// ─── Strategic header (shared by both templates) ────────────────────────

function ecomStrategicHeader(params: ScriptParams, dateIso: string): string {
  return `### 1. BRIEF INFO
| Field | Value |
|-------|-------|
| Brief ID | [Generate: PRODUCT_FUNNEL_ConceptSlug_v1, e.g., ES_TOF_DentTest_v1] |
| Date | ${dateIso} |
| Product | ${productLabel(params.product)} |
| Collection | [Specific collection/patterns or "Various"] |
| Collection Asset | [Specific patterns/colors needed for demo and reveal beats] |
| Format | 9:16 vertical (Reels/Stories), 1:1 secondary |

### 2. STRATEGY
| Field | Value |
|-------|-------|
| Concept | [The creative concept this brief executes — what is this ad about?] |
| Angle | [The strategic angle / talking point — the emotional or logical frame] |
| Awareness Level | ${params.awarenessLevel} (${params.funnelStage}) |
| Primary Emotion | [Derived from concept — Relief, Hope, Confidence, Independence, Trust, etc.] |
| Avatar | [The specific person — e.g., "Nurse, 52, who's accepted leg pain as part of the job"] |
| Landing Page | [${params.product} Collection] |

### 3. OFFER
| Field | Value |
|-------|-------|
| Promo | ${promoLine(params.offer)} |
| Promo Asset | ${params.offer !== 'None' ? 'Standard end card' : 'None'} |
| Value Callout | ${valueCallout(params.offer)} |
| Urgency Element | [If applicable based on promo period, otherwise "None"] |`;
}

// ─── 1. Ecom Brief (Doc) — covers Ecom Style, Full AI, AI Podcast ───────

export function buildEcomTemplate(
  params: ScriptParams,
  dateIso: string,
  hasInspiration: boolean = false,
): string {
  return `## ECOM AD BRIEF OUTPUT FORMAT (Doc — Editing Path)

This is an EDITING BRIEF. The editor assembles the final ad using either existing footage (Ecom Style), AI-generated visuals (Full AI, AI Podcast), or some combination. The output structure below is the SAME for every editing brief — only the visual vocabulary changes per ad type.

${ecomAdTypeNuance(params.adType)}

---

## OUTPUT STRUCTURE — ECOM AD BRIEF (8 sections)

${ecomStrategicHeader(params, dateIso)}

### 4. EDITING INSTRUCTIONS
| Field | Value |
|-------|-------|
| Pacing | [Derived from concept — e.g., "Demonstration-focused. Opens on visual evidence. 40-50 seconds."] |
| Resolution | 9:16 primary, 1:1 secondary |
| Caption & Graphics | [Text overlay strategy — what key moments get captions, style notes] |
| Transitions | [Cut style — e.g., "Clean cuts. Zoom on evidence shots. Smooth reveal on solution."] |
| Music | [Mood, genre, energy — e.g., "Curious opening, building, warm resolution."] |
| Voiceover | AI Voiceover – [Tone description — e.g., "Warm, observational female voice."] |
| Asset | [Specific footage categories OR AI generation prompts needed for this brief] |
| Notes | [Production notes — what's most important about this brief's visual approach] |

### 5. SCRIPT (HOOKS) — 3 Variations
| # | Shot Type | Suggested Visual | Hook Line |
|---|-----------|-----------------|-----------|
| 1 | [footage tag OR AI shot label] | [conversational description, 8-20 words] | "[hook line — full natural sentence]" |
| 2 | [tag] | [description] | "[different hook approach]" |
| 3 | [tag] | [description] | "[different hook approach]" |

Each hook uses a DIFFERENT approach. Note the principle (e.g., "Hook 1 — Hopkins Selector").

### 6. SCRIPT (BODY)
| # | Shot Type | Suggested Visual | Script Line |
|---|-----------|-----------------|-------------|
| 1 | [tag] | [conversational description, 8-20 words] | "[line — must sound like a real person talking]" |
| 2 | ... | ... | ... |

Row count adapts to concept and duration. Each row = ONE thought, ONE breath.

### 7. KEY DATA POINTS
List every statistic and customer quote referenced in the script, with source frequencies.

### 8. HOW ${params.framework.toUpperCase()} WAS APPLIED
Walk through how the framework maps to specific rows in the body. Reference row numbers.${hasInspiration ? `

### 9. VISUAL SUBSTITUTION LOG

An inspiration ad was pinned. Document any visual substitutions where the reference used a shot we don't have and you chose the closest available alternative.

| # | Inspiration Shot | Our Substitute | Rationale (1 sentence) |
|---|------------------|----------------|------------------------|
| 1 | [Reference visual] | [Shot Type from our library] | [Why this preserves intent] |

If NO substitutions were required, state: **"No substitutions required — all visuals sourced from available footage."**` : ''}`;
}

// ─── 2. AGC Brief (CSV) — covers all production briefs ──────────────────

export function buildAgcTemplate(params: ScriptParams): string {
  return `## AGC PRODUCTION BRIEF OUTPUT FORMAT (CSV — Production Path)

This is a PRODUCTION BRIEF. Nora finds talent, books a set, and films it. The output structure below is the SAME for every production brief — only the strategic content + nuance changes per ad type.

${agcAdTypeNuance(params.adType)}

---

## GENERAL AGC RULES (apply to every production brief)

- **Building Block label on every row** — hooks and body. The label explains the row's strategic purpose in the persuasion arc (Benefits, Problem, Solution, Curiosity, Reactions, Deposition, Bizarre, Satisfying, Pain Showcase, Twist the Knife, Reveal, Proof, Testimonial, Social Proof, Story telling, Relatable, CTA, etc.).
- **Short Lines Rule** — each row = ONE thought, ONE breath. If you'd pause mid-sentence, SPLIT into two rows. No long sentences crammed into one row.
- **Format Consistency** — all speaking rows use the same Shot Type (ON CAMERA for face-to-camera; SCRIPT for VO/POV). BROLL rows for visual-only cutaways between speaking rows.
- **9-Hook Matrix** — exactly 9 hooks per brief (3 Visuals × 3 Verbals).
- **Use REAL customer language** — every line must be built from the actual review data, not generic copywriter prose.

## OUTPUT STRUCTURE — AGC PRODUCTION BRIEF

### 1. STRATEGY SECTION
- **Concept:** [The creative concept — what is this ad about, what story does it tell?]
- **Angle:** [The strategic angle — the emotional/logical frame]
- **Avatar:** [Who is on screen — age range, look, energy, wardrobe, personality]
- **Location:** [Where the shoot takes place — be specific about the environment, per ad type nuance above]
- **Product:** ${productLabel(params.product)}
- **Collection:** [Specific collection/patterns if relevant, or "Various"]
- **Promotion:** [Promo period if any, or "Evergreen"]
- **Offer:** ${promoLine(params.offer)}
- **Pacing:** [${params.agcPacing === 'fast' ? 'Fast (15-30s) — punchy cuts, high energy' : params.agcPacing === 'deliberate' ? 'Deliberate (60-90s) — documentary rhythm, let moments breathe' : 'Standard (30-45s) — balanced pacing'}]
- **Music:** [Music direction — mood, genre, instruments, energy level]
- **Assets:** [Specific props, products, materials needed for the shoot]
- **Additional Notes:** [Production notes, special requirements, creative direction, anything Nora needs]

### 2. HOOKS — 9-Hook Matrix (3 Visuals × 3 Verbals)

First describe each Visual approach and each Verbal hook strategy:

**Visual A:** [Description of first camera setup/location/opening visual]
**Visual B:** [Description of second — genuinely DIFFERENT from A]
**Visual C:** [Description of third — genuinely DIFFERENT from A and B]
**Verbal 1:** [First hook line strategy]
**Verbal 2:** [Second hook line strategy — different emotional trigger]
**Verbal 3:** [Third hook line strategy — different emotional trigger]

Then output all 9 hooks as a markdown table:

| Hook | Building Block | Shot Type | Shot Angle | Talent Notes | Shot Notes | Shot Visual | Lines | Editing Notes | Caption |
|------|----------------|-----------|------------|--------------|------------|-------------|-------|---------------|---------|
| A1 | [label] | [type] | [angle] | [direction] | [technical] | [what viewer sees] | [spoken words] | [post notes] | [on-screen text] |
| A2 | ... | ... | ... | ... | ... | ... | ... | ... | ... |
| A3 | ... | ... | ... | ... | ... | ... | ... | ... | ... |
| B1 | ... | ... | ... | ... | ... | ... | ... | ... | ... |
| B2 | ... | ... | ... | ... | ... | ... | ... | ... | ... |
| B3 | ... | ... | ... | ... | ... | ... | ... | ... | ... |
| C1 | ... | ... | ... | ... | ... | ... | ... | ... | ... |
| C2 | ... | ... | ... | ... | ... | ... | ... | ... | ... |
| C3 | ... | ... | ... | ... | ... | ... | ... | ... | ... |

### 3. BODY SECTION
The main script body. 20-40 rows depending on pacing. Each row = ONE thought, ONE breath.

| # | Building Block | Shot Type | Shot Angle | Talent Notes | Shot Notes | Shot Visual | Lines | Editing Notes | Caption |
|---|----------------|-----------|------------|--------------|------------|-------------|-------|---------------|---------|
| 1 | [label] | [type] | [angle] | [direction] | [technical] | [what viewer sees] | [spoken words] | [post notes] | [on-screen text] |
| 2 | ... | ... | ... | ... | ... | ... | ... | ... | ... |

${params.agcBodyFormat === 'face-to-camera' ? '**Body Format: Face-to-Camera.** ALL speaking rows use Shot Type = ON CAMERA. Talent speaks directly to camera, face visible.' : "**Body Format: POV (Voiceover Narration).** ALL speaking rows use Shot Type = SCRIPT. Talent's voice is heard as VO but they are NOT on camera speaking. Camera shows hands, product, environment."}
BROLL rows (visual-only cutaways) may appear in either format as brief interruptions between speaking rows.

### 4. EXTRA B-ROLL LIST
8-12 additional shots for editing flexibility (NOT in the main body):

| # | Shot Type | Shot Angle | Shot Notes | Shot Visual | Editing Notes |
|---|-----------|------------|------------|-------------|---------------|
| 1 | BROLL | [angle] | [technical] | [what viewer sees] | [how editors might use this] |

### 5. HOW ${params.framework.toUpperCase()} WAS APPLIED
Walk through how the framework maps to the Building Block sequence in the body. Reference specific row numbers and Building Block labels.`;
}

// ─── Public router ──────────────────────────────────────────────────────

/**
 * Build the output-format markdown block for a given ad type. Routes to
 * one of the two real templates (Ecom Doc / AGC CSV) and injects the
 * ad-type nuance block so the strategic content is tailored even though
 * the OUTPUT STRUCTURE is the same. Static is handled separately in
 * scriptPrompt.ts (single-image format, not a video brief).
 */
export function buildBriefTemplateOutputFormat(
  params: ScriptParams,
  dateIso: string,
  hasInspiration: boolean = false,
): string {
  const id = getBriefTemplateId(params.adType);
  return id === 'agc'
    ? buildAgcTemplate(params)
    : buildEcomTemplate(params, dateIso, hasInspiration);
}
