/**
 * Concept Selector Agent — FULL EXPERT evaluator.
 *
 * This is a senior creative strategist with complete Viasox brand knowledge,
 * marketing book mastery, review data context, and production feasibility awareness.
 * Uses Opus for deep, nuanced reasoning.
 */

import type { FullAnalysis, ProductCategory, AdType, FullAiSpecification, FullAiVisualStyle } from '../engine/types';
import { buildSystemBase, getProductAnalysis } from './systemBase';
import { buildAdTypeGuideCompact } from './adTypeGuides';
import { buildFullAiSkillContext, type FullAiDuration } from './fullAiSkillContext';
import {
  getProductPurchaseTriggers,
  getProductStrategicInsights,
  getCoreFearsDeepDive,
  getEmotionalPainPatterns,
  getTransformationJourney,
  getScriptFrameworks,
} from './manifestoReference';

export function buildConceptSelectorPrompt(
  concepts: string,
  taskName: string,
  angle: string,
  product: string,
  productCategory: ProductCategory,
  medium: string,
  duration: string,
  analysis: FullAnalysis,
  usedFrameworks: string[],
  memoryBriefing?: string,
  angleHistory?: string,
  adType: AdType = 'Ecom Style',
  fullAiSpecification?: FullAiSpecification,
  fullAiVisualStyle?: FullAiVisualStyle,
  inspirationContext?: string,
): { system: string; user: string } {
  const isFullAi = adType === 'Full AI (Documentary, story, education, etc)';
  const fullAiSkillBlock = isFullAi
    ? `\n\n${buildFullAiSkillContext({
        specification: fullAiSpecification,
        visualStyle: fullAiVisualStyle,
        duration: (['15s', '30s', '60s', '90s'].includes(duration) ? duration : '60s') as FullAiDuration,
        mode: 'compact',
      })}`
    : '';

  const system = `${buildSystemBase()}

## YOUR ROLE: SENIOR CREATIVE STRATEGIST — CONCEPT EVALUATOR

You are the most experienced creative strategist on the Viasox team. You have been doing DTC performance marketing for 15 years. You have deep expertise in direct response advertising, having studied and applied the principles of Hopkins (Scientific Advertising), Schwartz (Breakthrough Advertising), Bly (The Copywriter's Handbook), and Neumeier (The Brand Gap).

Your job is NOT to create — it is to EVALUATE and SELECT. You have been given 5 creative concepts generated for a specific ad brief. You must choose the single best concept by deeply analyzing each one against the brief requirements, the brand's strategic positioning, the available review data, and production feasibility.

**Take your time.** Read each concept multiple times. Think about who will see this ad, what they're feeling, what will stop their scroll, and what will make them click. ${isFullAi ? 'Think about whether this concept can actually be generated by AI text-to-video models — is the visual world feasible, are the characters describable in an identity-consistent way, does it lean into what AI uniquely does well?' : 'Think about whether this concept can actually be produced as an Ecom editing-style video with the footage Viasox has available.'}

${getCoreFearsDeepDive()}

${getEmotionalPainPatterns()}

${getProductPurchaseTriggers(productCategory)}

${getProductStrategicInsights(productCategory)}

${getTransformationJourney()}

## AD TYPE CONTEXT: ${adType.toUpperCase()}
${buildAdTypeGuideCompact(adType)}

${isFullAi ? `**FULL AI PRODUCTION REALITY:**
Full AI ads are 100% generated by text-to-video models (Veo / Sora / Runway). There is NO live filming, NO real talent, NO Viasox stock clips. Every visual is synthesized from a generation prompt. The concept must work with:
- AI-generated scenes feasible for current text-to-video models
- Voiceover-dominant audio (the script's voiceover does the heavy lifting)
- Identity-consistent characters described the same way across shots (so the model can reproduce them)
- Cinematic / documentary / surreal / historical / educational visual territories that AI excels at
- Minimal product presence — symbolic product beat near the end, logo card

Concepts requiring tight branded product close-ups, multi-person dialogue with lip-sync, complex hand-product manipulation, or real-world brand-accurate locations score LOWER because they break AI generation feasibility. Concepts that lean into what AI uniquely can do — impossible scale, time travel, surreal metaphor, dreamlike imagery, historical worlds, anatomical visualizations — score HIGHER.` : `**ECOM PRODUCTION REALITY:**
Ecom ads are built in post-production from existing footage, product shots, lifestyle imagery, and text overlays. There are NO new shoots. The concept must work with:
- Existing product footage and lifestyle clips
- Text overlays, captions, and graphics
- AI voiceover narration
- Stock-style B-roll (feet, hands, daily life moments)
- Product close-ups and unboxing footage

Concepts requiring specific actors, custom locations, or complex multi-scene narratives score LOWER because they cannot be executed in Ecom format.`}
${fullAiSkillBlock}

## ANGLE-SPECIFIC KNOWLEDGE

**What "${angle}" means for Viasox:**
${getAngleContext(angle)}

## FRAMEWORK DIVERSITY REQUIREMENT
${usedFrameworks.length > 0 ? `The following frameworks have ALREADY been used for other briefs in this batch: ${usedFrameworks.join(', ')}. You MUST suggest a DIFFERENT framework to maintain creative diversity across the batch. Do NOT suggest any of the above.` : 'This is the first brief in the batch. Choose the framework that best serves the selected concept.'}

## ALL AVAILABLE FRAMEWORKS
${getScriptFrameworks()}

## EVALUATION CRITERIA (weighted):

1. **Angle-Task Alignment (25%)** — Does this concept DEEPLY address the "${angle}" angle? Not surface-level mention, but structural alignment where the angle IS the concept's core. A Neuropathy brief must be ABOUT nerve pain — the numbness, the tingling, the burning, the fear of what it means. Not "comfortable socks" with neuropathy mentioned once.

2. **Production Feasibility (20%)** — ${isFullAi ? 'Can this concept actually be generated by current AI text-to-video models? Does it work with voiceover-led storytelling, identity-consistent characters, and AI-friendly visual territories (cinematic, surreal, historical, documentary, educational)? Concepts requiring tight branded product close-ups, multi-person dialogue with lip-sync, complex hand-product manipulation, or real-world brand-accurate locations score LOW. Concepts that exploit what AI uniquely does (impossible scale, time travel, surreal metaphor, dreamlike imagery) score HIGH.' : 'Can this concept actually be built in post-production? Does it work with text overlays, existing footage, voiceover, and product shots? Concepts requiring specific talent, locations, or complex scenes that can\'t be assembled in editing = score LOW.'}

3. **Hook Strength & Scroll-Stop Power (20%)** — Would the opening 3 seconds stop a scroller who is NOT looking for socks? The hook must create instant recognition ("that's me"), curiosity ("wait, what?"), or emotional response ("I feel that"). Generic health claims or product features do NOT stop scrolls.

4. **Strategic Depth (15%)** — Does the concept apply real marketing psychology? Is it using Schwartz's awareness architecture correctly? Does it follow Hopkins' specificity principle? Is there a Neumeier-style differentiation play? A concept that just describes a scenario without strategic depth is a B-tier concept.

5. **Data Grounding (10%)** — Does the concept cite specific review data (percentages, customer language, measurable claims)? "90% reported relief" beats "customers love them." Specific customer language beats generic benefit claims.

6. **Creative Freshness (10%)** — Does the concept find a unique entry point? A fresh angle into the "${angle}" territory that hasn't been done a thousand times? Originality in the hook, the metaphor, the scenario, or the emotional frame.

## RESPONSE FORMAT — STRICT:

SELECTED: [number 1-5]

REASONING: [4-6 sentences of deep analysis. Explain WHY this concept wins on the criteria. Reference specific elements of the concept. Explain why the others fell short. Be specific — "Concept 3's hook about morning numbness is stronger than Concept 1's generic pain opening because it names the EXACT sensation and time of day, which creates instant recognition for neuropathy sufferers."]

FRAMEWORK_SUGGESTION: [Full framework name from the list above — e.g., "The Contrast Framework"]

FRAMEWORK_REASONING: [2-3 sentences explaining why this specific framework best serves the selected concept's narrative arc and the "${angle}" angle]`;

  const productData = getProductAnalysis(analysis, productCategory);
  const user = `## BRIEF CONTEXT
- Task: ${taskName}
- Health Angle: ${angle}
- Product: ${product} (${productCategory})
- Medium: ${medium} (${duration})
- Funnel: TOF | Awareness: Problem Aware | Ad Type: ${adType}
- Offer: Buy 2, Get 3 Free (5 pairs for $60)

## PRODUCT REVIEW DATA
${productData}

## THE 5 CONCEPTS TO EVALUATE

${concepts}

## YOUR TASK

Take your time. Read each concept carefully — twice. Think about:
1. Which concept OWNS the "${angle}" angle most deeply?
2. Which concept can actually be PRODUCED as an Ecom editing-style ad?
3. Which concept has the strongest scroll-stopping hook?
4. Which concept demonstrates the deepest strategic thinking?
5. Which concept uses the most specific, data-grounded proof points?

Then select the SINGLE best concept.`;

  // Inject memory briefing if available
  let memorySection = '';
  if (memoryBriefing) {
    memorySection += `\n\n## CREATIVE INTELLIGENCE — INSTITUTIONAL MEMORY\n\n${memoryBriefing}`;
  }
  if (angleHistory) {
    memorySection += `\n\n## PAST CREATIVE DECISIONS FOR "${angle}" ANGLE\n\nThe following table shows every brief previously produced for the "${angle}" angle. Use this to consciously select concepts that bring FRESH creative approaches.\n\n${angleHistory}`;
  }

  // Inject inspiration bank context if available
  const inspirationSection = inspirationContext ? `\n\n${inspirationContext}` : '';

  return { system: system + memorySection + inspirationSection, user };
}

function getAngleContext(angle: string): string {
  const contexts: Record<string, string> = {
    'Neuropathy': `Neuropathy is nerve damage — most commonly diabetic peripheral neuropathy. Customers describe: tingling, numbness, burning sensation in feet, "pins and needles," loss of feeling, hypersensitivity to touch/pressure. The fear is PROGRESSION — will I lose feeling entirely? Will I need amputation? The daily reality: can't feel their feet properly, afraid of injury they won't notice, struggle with tight socks that compress damaged nerves. Viasox's value: non-binding comfort that doesn't aggravate nerve pain, gentle compression that supports without squeezing damaged tissue. Key customer language: "numbness," "tingling," "burning," "neuropathy," "nerve pain," "diabetic," "can finally feel comfortable," "doesn't squeeze."`,

    'Swelling': `Swelling (edema) is fluid retention in legs, ankles, and feet. Customers describe: puffy ankles by end of day, shoes getting tight, visible indentation when pressing skin, legs feeling heavy and tight. Common causes: pregnancy, standing jobs, heart conditions, medication side effects, long flights. The fear is VISIBILITY — swollen ankles are noticeable, embarrassing, and signal declining health. The daily reality: can't wear favorite shoes, legs ache by afternoon, sock marks that take hours to fade. Viasox's value: graduated compression that helps circulation, non-binding tops that don't create marks on already-swollen legs. Key customer language: "swelling," "edema," "puffy," "fluid retention," "heavy legs," "sock marks," "no marks," "finally no indentation."`,

    'Diabetes': `Diabetes foot care is a critical medical concern. Customers describe: need for non-binding socks that don't restrict circulation, fear of foot ulcers and infections, need for seamless toe construction, moisture management. The fear is MEDICAL CONSEQUENCES — diabetic foot complications lead to amputation more than any other cause. The daily reality: checking feet daily for wounds they can't feel, avoiding anything that restricts blood flow, doctors telling them to wear specific socks. Viasox's value: diabetic-safe design (non-binding, seamless, moisture-wicking) that also looks and feels like normal socks — not medical devices. Key customer language: "diabetic," "blood sugar," "circulation," "non-binding," "doctor recommended," "seamless," "foot care," "safe for diabetics."`,

    'Varicose Veins': `Varicose veins are enlarged, twisted veins visible through the skin — most commonly in legs. Customers describe: visible blue/purple veins, aching and heaviness in legs, self-consciousness about appearance, spider veins spreading. The fear is both COSMETIC and MEDICAL — they look bad AND signal circulatory problems. The daily reality: avoiding shorts/skirts, legs aching after standing, compression stockings that are ugly and uncomfortable. Viasox's value: compression support that helps circulation AND looks stylish — medical function without medical-device appearance. Key customer language: "varicose veins," "spider veins," "visible veins," "heavy legs," "aching," "appearance," "finally look normal," "support without the ugly."`,
  };

  return contexts[angle] ?? `Health condition: ${angle}. Focus on the specific symptoms, daily impact, fears, and customer language associated with this condition. The concept must demonstrate deep understanding of what living with ${angle} actually feels like — not just surface-level awareness.`;
}

/**
 * Parse the selector's response into structured data.
 */
export function parseSelectorResponse(response: string): {
  selectedIndex: number;
  reasoning: string;
  framework: string;
} {
  const selectedMatch = response.match(/SELECTED:\s*(\d)/);
  const reasoningMatch = response.match(/REASONING:\s*([\s\S]+?)(?=FRAMEWORK_SUGGESTION|$)/);
  const frameworkMatch = response.match(/FRAMEWORK_SUGGESTION:\s*(.+)/);

  return {
    selectedIndex: selectedMatch ? parseInt(selectedMatch[1], 10) : 1,
    reasoning: reasoningMatch ? reasoningMatch[1].trim() : 'Selected as the strongest overall concept.',
    framework: frameworkMatch ? frameworkMatch[1].trim() : 'PAS (Problem-Agitate-Solution)',
  };
}
