/**
 * Full AI Skill Context — adapted from the viasox-ai-doc-briefs Claude Skill.
 *
 * This module encodes the institutional knowledge of the AI Documentary brief
 * methodology in a parameterized form so it can adapt to:
 *
 *   - DURATION       — 15s / 30s / 60s / 90s (selected by user or autopilot)
 *   - SPECIFICATION  — Documentary / Historical / Educational / Emotional Story / Aspirational
 *   - VISUAL STYLE   — 5 Full AI visual treatments
 *   - MODE           — 'compact' (concept generation, selection) or 'full' (script writing)
 *
 * The skill was originally written for 2-3 minute documentary ads, but the
 * Viasox autopilot pipeline produces a wider range of formats. This module
 * scales the methodology up and down so the same body of expertise applies
 * whether the brief is 15 seconds or 90.
 *
 * USAGE:
 *   import { buildFullAiSkillContext } from './fullAiSkillContext';
 *
 *   const skillContext = buildFullAiSkillContext({
 *     specification: 'Documentary',
 *     visualStyle: 'Story with cohesive characters',
 *     duration: '60s',
 *     mode: 'full',
 *   });
 *
 *   // Append to the Full AI directive in anglesPrompt / scriptPrompt / conceptSelectorPrompt
 */

import type { FullAiSpecification, FullAiVisualStyle } from '../engine/types';

export type FullAiSkillMode = 'compact' | 'full';
export type FullAiDuration = '15s' | '30s' | '60s' | '90s';

export interface FullAiSkillContextParams {
  /** Selected specification (narrative mode). Defaults to 'Documentary'. */
  specification?: FullAiSpecification;
  /** Selected visual style. Defaults to 'Story with cohesive characters'. */
  visualStyle?: FullAiVisualStyle;
  /** Brief duration. */
  duration: FullAiDuration;
  /** 'compact' for concept generation/selection; 'full' for script writing. */
  mode: FullAiSkillMode;
}

export function buildFullAiSkillContext(params: FullAiSkillContextParams): string {
  const spec: FullAiSpecification = params.specification ?? 'Documentary';
  const style: FullAiVisualStyle = params.visualStyle ?? 'Story with cohesive characters';
  const sections: string[] = [];

  sections.push(SKILL_HEADER);
  sections.push(getUniversalRules(params.mode));
  sections.push(getSpecificationPlaybook(spec, params.mode));
  sections.push(getVisualStylePlaybook(style, params.mode));
  sections.push(getDurationPacing(params.duration, spec, params.mode));

  if (params.mode === 'full') {
    sections.push(QUALITY_BAR);
    sections.push(AUDIT_CHECKLIST);
  }

  return sections.join('\n\n');
}

// ─── Skill Header ────────────────────────────────────────────────────────────

const SKILL_HEADER = `## ⚡ FULL AI SKILL CONTEXT — VIASOX AI DOCUMENTARY METHODOLOGY

The following is the distilled institutional methodology for Viasox Full AI ads, adapted from the viasox-ai-doc-briefs creative skill. This methodology was reverse-engineered from the reference grounding/earthing documentary ads that defined the format and refined through testing. **Apply it.**`;

// ─── Universal Rules (always injected) ───────────────────────────────────────

function getUniversalRules(mode: FullAiSkillMode): string {
  const intro = `### UNIVERSAL RULES — APPLY TO EVERY FULL AI ${mode === 'full' ? 'SCRIPT' : 'CONCEPT'}, REGARDLESS OF SPECIFICATION OR VISUAL STYLE`;

  return `${intro}

**1. ESTABLISH BEFORE DESCRIBE — THE NON-NEGOTIABLE PRINCIPLE.**

Every pain point, symptom, scary detail, or condition reference in the ${mode === 'full' ? 'script' : 'concept'} must have an established cause-and-effect chain BEFORE it appears. Without that chain, the line lands flat — even if the language is good.

The audit question for every pain point: **"Why does this matter? Why is this a real problem for this customer?"** If the ${mode === 'full' ? 'script' : 'concept'} has not already answered that question by the time the line appears, the line needs to be moved later — or a new line needs to be inserted earlier to establish the cause.

**Bad pattern:** "It starts in the toes — tingling, numbness, burning. Doctors call it peripheral neuropathy."
**Good pattern:** "Diabetes destroys the tiny blood vessels that feed your nerves. The vessels narrow. The blood slows. And the nerves farthest from your heart — the ones in your feet — are the first to be cut off. They send distress signals: tingling, burning, numbness."

The "Line A (cause) → Line B (symptom)" order is mandatory. Always. Even if the dramatic version reads better in reverse, resist it. The dramatic version doesn't work for unaware/problem-aware audiences.

**2. AI GENERATION FEASIBILITY.**

100% of footage is AI-generated by text-to-video models (Veo / Sora / Runway / Kling). There is NO live filming, NO real talent, NO Viasox stock clips except possibly a brief product beat at the end.

✅ AI excels at: anatomical interior visualizations, microscopic/cellular views, historical scenes, body silhouettes with illuminated systems, conceptual visualizations (blood flow, signal transmission), evocative sensory imagery, surreal/dreamlike worlds, cinematic landscapes.

❌ AI struggles with: tight branded product close-ups with brand-accurate detail, multi-person dialogue with lip-sync, complex hand-product manipulation, real-world brand-accurate locations, sustained character continuity across many shots without explicit identity descriptions.

Every visual you describe must be feasible for current AI text-to-video models. If it requires an actor doing something specific with a specific real product, it doesn't belong in a Full AI ad.

**3. NO MEDICAL CLAIMS.**

Viasox cannot make medical treatment claims. Frame everything as **"support"** and **"improved circulation"**, never **"treatment"** or **"cure"**. Any line that promises to "cure," "heal," "treat," "stop," or "fix" a medical condition must be reframed.

✅ "Give your nerves the freedom they need." | "Support for tired legs." | "Helps improve circulation."
❌ "Treats neuropathy." | "Heals nerve damage." | "Cures swelling."

**4. HOOKS LEAD WITH CAUSE, NEVER WITH SYMPTOMS.**

The hook must do three things in 2-4 sentences: establish context (who is the viewer, what should they care about), present a striking fact/image/contrast, and implicitly promise that a story is coming.

✅ "If you have diabetes, your nerves are already under attack..." (cause-led)
✅ "2,400 years ago, a Greek physician discovered..." (history-led)
✅ "There are over 7,000 nerve endings in each of your feet..." (wonder-led)
❌ "If you have tingling in your feet..." (symptom-led — banned)
❌ "Sock marks. Tingling. Numbness. Sound familiar?" (symptoms without context — banned)
❌ "Did you know..." / "What if I told you..." (generic openers — banned)

The hook NEVER mentions the product, the brand, or the offer. The whole point of the format is delayed gratification.

**5. THE PROTAGONIST (when shown) IS A WOMAN 50+.**

Even in AI-generated worlds, the on-screen human (if shown) must be a believable 50+ woman. Describe her in enough detail in the FIRST shot for identity-consistent generation: approximate age, hair color/style, build, clothing palette, environment. Reference back to the SAME woman in every subsequent shot ("the same woman from before, now in...") so the AI generator can maintain identity continuity.`;
}

// ─── Specification Playbooks ─────────────────────────────────────────────────

function getSpecificationPlaybook(spec: FullAiSpecification, mode: FullAiSkillMode): string {
  switch (spec) {
    case 'Documentary':
      return getDocumentaryPlaybook(mode);
    case 'Historical':
      return getHistoricalPlaybook(mode);
    case 'Educational':
      return getEducationalPlaybook(mode);
    case 'Emotional Story':
      return getEmotionalStoryPlaybook(mode);
    case 'Aspirational':
      return getAspirationalPlaybook(mode);
    default:
      return getDocumentaryPlaybook(mode);
  }
}

function getDocumentaryPlaybook(mode: FullAiSkillMode): string {
  const compact = `### SPECIFICATION PLAYBOOK — DOCUMENTARY (NETFLIX-DOC MODE)

The Documentary specification is the format the source skill was built for. It's a deliberate emotional and intellectual journey from curiosity → recognition → action, with no sense that it's an ad until the very end.

**Tone:** Warm, intelligent, fascinated narrator. Never selling. Teaching. The viewer should momentarily forget this is an ad.

**Structure: The 8-Stage Documentary Arc.**

The arc is the spine. Skipping a stage = the ad feels incomplete. Scrambling the order = the emotional beats don't land.

1. **THE HOOK** — Striking image + sentence promising a story. Establishes context for who/what to care about. Earns attention.
2. **THE WONDER** — Frame the body part / system as something amazing. Make the viewer fall in love with their feet/nerves/circulation BEFORE telling them anything is wrong. Sensory language, anatomical detail, beautiful AI visuals.
3. **THE HISTORY** — Ground the central insight in something ancient and human. A Greek physician 2,400 years ago. A Roman discovery. Lost wisdom. Establishes credibility AND allows for visually rich AI imagery (candlelit chambers, classical art, ancient scenes).
4. **THE SCIENCE** — Bridge from history to modern science. Explain how the system works WHEN HEALTHY. Clean, clear, slightly technical. Beautiful medical visualizations. Sets up the contrast for the next stage.
5. **THE CAUSE** — The most important stage. WHY does the problem happen? What mechanism breaks? What condition triggers it? Who is at risk? **Without this stage, every subsequent symptom lands flat.**
6. **THE PROBLEM** — Now (and only now) describe symptoms, daily reality, the experience. End with a moment of recognition: "that's me."
7. **THE BRIDGE** — Product introduced as the natural answer. Not as a sales pitch — as the obvious solution to the problem you've already established. Almost inevitable.
8. **THE PROOF + CTA** — Proof points (this is the only stage where real product footage may appear, but in Full AI mode it's an AI-rendered product beat), offer (Buy 2 Get 3 Free), final emotional callback to the opening visual for closure.

**Education-to-product ratio:** 65-75% of runtime is stages 1-6 (educational). 25-35% is stages 7-8 (product reveal). If the product appears too early, the ad becomes sales-y and breaks the format.`;

  if (mode === 'compact') return compact;

  return `${compact}

**Pick the central insight FIRST.** Every great Documentary ad is built around ONE central insight — a fact, history, or piece of science most people don't know but immediately recognize as important once they hear it. The insight should:
- Connect to a real customer pain
- Be TRUE (you cannot fabricate science or history)
- Be fascinating on its own, even without the product
- Lead naturally to the product as the answer

The insight is the "spine" — everything builds from it. Examples (don't reuse literally):
- "Your nervous system was discovered by a Greek physician 2,400 years ago — and he proved that nerves need blood to survive."
- "Your feet contain more nerve endings per square inch than almost anywhere else in your body."
- "Roman soldiers wrapped their legs in linen to march thousands of miles without their feet failing — they knew something about circulation we've forgotten."

**Tone shifts:** Documentary narrator throughout stages 1-6. Warmer, more conversational ONLY in stages 7-8 (the product reveal). Don't make the documentary section feel like an ad, and don't make the product section feel like a textbook.

**The transition from AI-generated educational visuals to the product reveal is the format's signature beat.** It's where "mystical documentary" crosses into "tangible solution." Don't rush it. Let the viewer feel the shift.

**End with a single emotional callback line** that ties back to the central insight or the opening visual. This is what makes the ad feel like a complete piece of storytelling rather than a video that just ended.`;
}

function getHistoricalPlaybook(mode: FullAiSkillMode): string {
  const compact = `### SPECIFICATION PLAYBOOK — HISTORICAL

Historical mode reaches into the past to illuminate the present. It uses period-accurate settings, archival aesthetics, and a journey through time to ground the product story in something ancient and authoritative.

**Tone:** Reverent, slightly mythic, knowledgeable. Like a history channel narrator who genuinely loves their subject. The voice should feel like it's revealing something the audience should have known.

**Structure: The Time-Travel Arc.**

1. **THE HOOK** — Anchor in a specific historical moment, figure, or place. "In 1812, at the Battle of Borodino..." "In ancient Egypt, a physician named Imhotep..." Make the viewer feel they've stepped into another era.
2. **THE WORLD** — Build the historical world. Costumes, architecture, daily life. AI excels at this — lean into period-accurate visual richness.
3. **THE INSIGHT** — Reveal what these ancient/historical people understood about the body, circulation, foot care, or whatever the angle is. Cite real history. Don't fabricate.
4. **THE LOSS** — What did we forget? What does modern life ignore that the ancients knew? This is where you create the sense of "lost wisdom."
5. **THE PRESENT** — Bridge to modern life. The same problem the ancients solved is the problem the viewer is living with now — but they don't have the ancient solution.
6. **THE REDISCOVERY** — Viasox as the modern application of the ancient principle. Not as "we invented this" — as "we're returning to what worked."
7. **THE CTA** — Quiet, confident. The viewer has just been on a journey through history; they don't need to be sold to.

**Critical:** Every historical claim must be plausibly accurate. Don't invent dates, figures, or discoveries. Real history gives the ad gravity. Fabricated history collapses the format on the first viewer who Googles it.`;

  if (mode === 'compact') return compact;

  return `${compact}

**Visual treatment:** Period-accurate is the non-negotiable. Costumes, lighting (candlelight, oil lamps, daylight through ancient windows), architecture, props. AI is exceptional at this — describe shots with deep specificity ("dimly-lit ancient Greek physician's chamber, scrolls and bronze instruments on a wooden table, late afternoon golden light through a window with a view of the sea") and the model will deliver.

**Voiceover style:** Warm, slightly slower pacing. Treat each line as a fragment of a larger story being recounted. Allow pauses. The audience should feel time passing.

**Common historical anchors that work for Viasox:**
- Ancient Greek/Roman medicine (Hippocrates, Galen, Imhotep)
- Roman military (foot care for marching armies)
- Medieval/Renaissance physicians (early circulation theory, William Harvey)
- WWI/WWII nursing (compression therapy, foot care for soldiers and shift workers)
- Ancient Eastern medicine (acupuncture, traditional understanding of circulation)

Pick one anchor. Don't try to span centuries — go deep on one moment.

**Closing:** The CTA should feel like the natural conclusion of a documentary, not a hard sell. "After 2,400 years, the answer is finally easy. Viasox EasyStretch. Buy two, get three free." Calm. Confident. Inevitable.`;
}

function getEducationalPlaybook(mode: FullAiSkillMode): string {
  const compact = `### SPECIFICATION PLAYBOOK — EDUCATIONAL

Educational mode teaches the viewer something genuinely valuable about their body, their condition, or how something works — and earns the product reveal by giving knowledge first.

**Tone:** Clear, slightly academic, generous. Like a great science communicator (think Hank Green, but for the 50+ female audience). Never condescending.

**Structure: The Teaching Arc.**

1. **THE HOOK** — Lead with a question the viewer suddenly wants answered, OR a fact that flips their assumption. "Your feet have more sweat glands than any other part of your body — and that's not a bad thing."
2. **THE LESSON** — Set up what you're about to teach. "Here's how the lymphatic system actually works." Frame it as a gift of knowledge, not a sales setup.
3. **THE EXPLANATION** — Walk through the concept clearly using AI-generated visualizations (anatomical interiors, cell-level views, slow conceptual animations of blood flow / lymph drainage / nerve signaling). Use metaphors that simplify without dumbing down.
4. **THE INSIGHT** — The "aha" moment. Where the teaching leads to a realization the viewer didn't have before.
5. **THE APPLICATION** — How this knowledge applies to the viewer's daily life. What they should do differently now that they understand.
6. **THE PRODUCT AS APPLICATION** — Viasox as the concrete tool that puts the lesson into practice. Not as "the answer" — as "what someone who understands this would use."
7. **THE CTA** — Knowledge-led. "Now that you know how it works, treat your feet accordingly. Viasox EasyStretch."

**The viewer should leave smarter, even if they don't buy.** That's the brand value of educational content — it builds trust by giving without expecting.`;

  if (mode === 'compact') return compact;

  return `${compact}

**Visual treatment:** Clean medical/scientific visualizations. AI is excellent at:
- Cross-section anatomy (inside a leg, inside a foot, the lymphatic network)
- Microscopic views (red blood cells flowing through capillaries, nerve impulses firing)
- Conceptual animations (oxygen molecules transferring from blood to tissue, lymph being squeezed upward by muscle contraction)
- Side-by-side comparisons (healthy vs. compromised circulation)

Describe these shots with scientific specificity. "Macro shot of a single nerve fiber surrounded by capillaries, golden glow on the nerve, red blood cells flowing past, oxygen molecules transferring from blood to nerve, dark background, nature documentary lighting."

**Use real science.** Educational mode collapses if the science is wrong. Stick to well-established physiological concepts: how the lymphatic system drains, why circulation slows when we sit, what happens to nerves under sustained pressure, how compression assists venous return. You don't need to be a medical journal — but you can't make things up.

**Avoid medical claims.** This is especially important in Educational mode because the format invites authoritative statements. You can explain how something works. You cannot say a sock "treats" or "cures" anything. Frame the product as "support for the system you just learned about," not "the medical solution to the problem."

**Closing line:** Educational ads should end with a line that empowers the viewer's new knowledge, not a hard sell. "Your circulation is yours. Take care of it." Then offer + CTA.`;
}

function getEmotionalStoryPlaybook(mode: FullAiSkillMode): string {
  const compact = `### SPECIFICATION PLAYBOOK — EMOTIONAL STORY

Emotional Story mode is the closest the Full AI format gets to a short film. It's character-driven, intimate, and built around a small specific moment that unfolds into something universal.

**Tone:** Quiet, observational, unsentimental. The opposite of advertising. Trust the moment. Don't push the emotion — let it land naturally.

**Structure: The Short-Film Arc.**

1. **THE OPENING IMAGE** — A specific, intimate moment. A woman sitting on the edge of her bed, staring at her feet. Light through a window. A cup of coffee on the nightstand. Establish the WORLD before the story begins.
2. **THE ESTABLISHING DETAIL** — One small detail that suggests the bigger story without saying it. The pill bottles on the dresser. The cane by the door. The photo of her late husband.
3. **THE STRUGGLE (shown, not told)** — A silent action. She tries to put on her socks. The elastic catches her swollen ankle. She winces but doesn't make a sound. This is the "establish before describe" rule in visual form — show the cause and the effect without narrating it.
4. **THE TURN** — A small change. She remembers something. Sees something. Tries something. The product appears here, but only as part of the story — not as a sales beat.
5. **THE RELEASE** — The moment of relief. Subtle. A breath. A smile. A return to something she'd given up.
6. **THE CALLBACK** — Mirror the opening image, but transformed. Same window. Same coffee. But she's different now.
7. **THE CTA** — Almost whispered. The story did the work. The CTA just gives the viewer a way to act on what they just felt.

**Voiceover is minimal or absent.** This is the one specification where the visuals carry the story without heavy narration. If there IS a voiceover, it's sparse, poetic, and doesn't describe what we're already seeing.`;

  if (mode === 'compact') return compact;

  return `${compact}

**Character continuity is critical** — and it's the hardest thing for AI to do. Build the story around ONE protagonist whose appearance is described in obsessive detail in the very first shot, then referenced in every subsequent shot ("the same woman from before, now in the kitchen, same blue cardigan, same silver hair pulled back, but with a small smile she didn't have at the start").

**Lean into silence.** Emotional Story is the Viasox spec where you can have shots with NO voiceover, NO music, NO text — just the woman, the moment, the breath. Trust the viewer's attention. The format rewards stillness.

**The "small moment" is the whole point.** This isn't a montage of struggles. It's ONE morning. ONE moment of getting dressed. ONE walk to the window. The universal lives inside the specific. If you generalize, the emotion evaporates.

**Avoid:** dramatic music swells, narrator monologues about "millions of women like her," before/after split screens, voiceover that names emotions ("she felt relief"). Show. Don't tell.

**Closing:** The product appears almost as a prop, not a hero. The brand name is mentioned once, quietly, as the credits roll. "Viasox. For mornings like this one." Then offer. Then quiet.`;
}

function getAspirationalPlaybook(mode: FullAiSkillMode): string {
  const compact = `### SPECIFICATION PLAYBOOK — ASPIRATIONAL

Aspirational mode lifts the viewer. It's about beauty, freedom, dignity, and possibility. It paints a world the viewer wants to live in and shows the product as the threshold to that world.

**Tone:** Warm, hopeful, slightly elevated. Like the best lifestyle ads — but earned, not affected. The voice should feel like an invitation, not a sales pitch.

**Structure: The Aspirational Arc.**

1. **THE VISION** — Open with a beautiful, almost mythic image. Golden hour. Open landscape. A woman walking freely. Set the emotional ceiling for the entire ad.
2. **THE CONTRAST (gentle)** — Acknowledge the gap between the vision and the viewer's current reality. Don't dwell. A single line or visual that names the loss without wallowing.
3. **THE PROMISE** — Reframe the vision as accessible. "What if this was still yours?" Not as a question to dismiss — as a real possibility.
4. **THE REASON IT'S POSSIBLE** — Briefly establish the cause-and-effect chain that explains WHY the viewer has been excluded from the vision (their feet, their circulation, their comfort) AND why that can be different.
5. **THE BRIDGE** — The product as the small thing that opens the door to the big thing. Not "miracle socks" — "the small adjustment that makes the rest possible."
6. **THE NEW VISION** — The viewer in the world of the opening image. Walking the beach. Tending the garden. Holding her grandchild. The vision realized.
7. **THE CTA** — Generous, dignified. "You deserve this. Viasox EasyStretch. Buy two, get three free."

**The aspirational vision must be concrete.** Vague "freedom" doesn't move people. SPECIFIC freedom does. The garden she stopped tending. The walk to the lighthouse she used to take. The dance floor at her granddaughter's wedding. Pick ONE specific aspiration and build the entire ad around it.`;

  if (mode === 'compact') return compact;

  return `${compact}

**Visual treatment:** Cinematic, painterly, golden. AI does this beautifully:
- Golden hour landscapes (beaches, gardens, mountain trails)
- Soft window light (kitchens, bedrooms, sunrooms)
- Slow-motion natural movement (a hand brushing through tall grass, a foot stepping into morning surf)
- Architectural beauty (porches, bridges, doorways framed by light)

Describe these shots with cinematographer-level specificity. "Wide shot of an older woman walking barefoot along a wet beach at sunrise, low golden light raking across the sand, soft waves breaking, her silver hair lifted slightly by the breeze, the camera at ankle height tracking alongside her, anamorphic widescreen, painterly grade."

**Avoid the aspirational ad clichés:** the helicopter shot of a mansion, the white horse on a beach, the woman laughing with a salad. Aspirational ≠ rich. For Viasox's audience, aspirational is the small dignified life she thought she'd lost — the morning walk, the garden, the dance, the hand of her grandchild. Specific. Earned.

**Music direction:** Aspirational mode benefits from explicit music notes. "Warm minimal piano building to hopeful resolve." "Solo cello over ambient strings." Don't leave music to chance.

**Voiceover:** Sparser than Documentary. Let the visuals breathe. When the voice does come in, it should feel like a wise friend speaking gently. Not a brand. Not an expert. A friend.

**Closing line:** Speak directly to the viewer's aspirational identity. "You're not done yet. The next chapter starts with comfort. Viasox EasyStretch."`;
}

// ─── Visual Style Guides ─────────────────────────────────────────────────────

function getVisualStylePlaybook(style: FullAiVisualStyle, mode: FullAiSkillMode): string {
  switch (style) {
    case 'Story with cohesive characters':
      return getCohesiveCharactersGuide(mode);
    case 'Fully Voice Over':
      return getFullyVoiceOverGuide(mode);
    case 'Includes Talking To Camera':
      return getTalkingToCameraGuide(mode);
    case 'No Humans Shown (Perspective of the feet or socks)':
      return getNoHumansGuide(mode);
    case 'Historical Visuals and Claims':
      return getHistoricalVisualsGuide(mode);
    default:
      return getCohesiveCharactersGuide(mode);
  }
}

function getCohesiveCharactersGuide(mode: FullAiSkillMode): string {
  const base = `### VISUAL STYLE — STORY WITH COHESIVE CHARACTERS

A cohesive character (or characters) appears across the full ad — same face, same wardrobe, same world. The AI MUST maintain identity consistency across every shot.

**The non-negotiable:** Describe the protagonist in OBSESSIVE detail in the first shot. Then reference back to her in EVERY subsequent shot using the SAME description. The AI generator can only maintain identity consistency if you give it the same anchor every time.

**Required first-shot description:**
- Approximate age (e.g., "early 60s")
- Hair color, length, and style (e.g., "silver hair, shoulder-length, gently waved, tucked behind one ear")
- Build (e.g., "soft build, average height")
- Clothing palette (e.g., "warm cream cardigan over a pale blue blouse, dark slacks")
- Distinguishing features (e.g., "small reading glasses on a beaded chain, soft eyes")
- Environment (e.g., "morning kitchen with light from a window over the sink, plants on the sill")

**Reference pattern in subsequent shots:**
"Same woman from before — silver hair, cream cardigan, soft eyes — now in the garden, late afternoon light, kneeling beside the tomatoes."

The pattern works because the AI re-grounds itself in the same identity tokens each time.`;

  if (mode === 'compact') return base;

  return `${base}

**Wardrobe consistency:** Don't change her outfit unless the story REQUIRES it (and even then, describe the change explicitly). Same clothes across shots is the cheapest way to maintain identity.

**Camera language:** Vary angles and distances, but keep lighting and color grade consistent. The viewer should feel they're watching ONE story, not a montage of different shoots.

**Multiple characters:** Possible but harder. If you must have a second character (a daughter, a husband, a friend), describe them with the same level of detail and reference both consistently. Limit to two named characters max.

**Character arc:** The ONE character should change subtly across the ad. Posture shifts from tight to relaxed. Expression shifts from fatigued to peaceful. Same person, transformed by the story.`;
}

function getFullyVoiceOverGuide(mode: FullAiSkillMode): string {
  const base = `### VISUAL STYLE — FULLY VOICE OVER

No dialogue. No lip sync. No on-camera talking. 100% voiceover carries the story. The visuals are pure imagery — scenes, textures, moments — and the VO does the narrative work.

**Why this works:** Lip-sync is the hardest thing for AI text-to-video models. By committing to no on-camera speech, you eliminate the highest-risk element of AI generation entirely. Every shot is then optimized for visual prompt fidelity, not for matching mouth movements to a script.

**The voiceover is the ad.** Treat it like a great audiobook excerpt — every word chosen, every pause earned. The visuals deepen what the voice is saying; they don't replace it.

**Visual treatment:** This is where you go full cinematographer. Beautiful imagery. Slow movement. Texture, light, atmosphere. The viewer should feel like they're watching a poem with pictures.`;

  if (mode === 'compact') return base;

  return `${base}

**Narration writing rules:**
- Write for the EAR. Read every line out loud. If it doesn't sound natural spoken, rewrite.
- Vary sentence length. A short sentence after a long one creates rhythm.
- Use full natural sentences. Not fragments. Not copy-style bullets.
- Pauses are part of the script. Mark them: "She stopped. (pause) She listened."
- The narrator has a POV. Pick one (third-person omniscient, first-person observer, second-person direct address) and stick with it.

**Voice direction:** Always specify the VO style in the brief — "warm female voice, slightly raspy, late 50s, unhurried" or "documentary narrator male, middle aged, fascinated and warm." The VO casting is part of the creative direction.

**Music + sound design:** With no dialogue, music and sound design carry more weight. Specify music direction explicitly. Note ambient sounds (birds, wind, distant kitchen sounds, breath).

**Avoid:** narration that describes what the viewer is already seeing. If the shot shows a woman walking through tall grass, the VO shouldn't say "she walks through tall grass." It should say something the IMAGE doesn't say.`;
}

function getTalkingToCameraGuide(mode: FullAiSkillMode): string {
  const base = `### VISUAL STYLE — INCLUDES TALKING TO CAMERA

An AI-generated character speaks directly to the camera at least once. This is the highest-risk visual style for AI generation because it requires lip-sync — and current text-to-video models struggle with it.

**Critical risk-mitigation rules:**
1. **Talking-to-camera moments must be SHORT** — single sentences, not monologues. The longer the on-camera speech, the more visible the lip-sync errors become.
2. **The rest of the ad should be VO over imagery** — use the talking-to-camera moments as PUNCTUATION, not as the spine.
3. **Tight shots, natural gestures, soft lighting** — close-up framing helps the AI focus its rendering on the face. Generous lighting hides imperfections.
4. **Specify exactly what they say verbatim** — don't leave it to the AI to improvise. Write the line as it should appear, then write it again in the VO column for clarity.

**Use this style sparingly.** Most Full AI ads are stronger as Fully Voice Over. Talking to Camera should be reserved for moments where direct address creates real impact (a single line of recognition, a dare, a question pointed at the viewer).`;

  if (mode === 'compact') return base;

  return `${base}

**The strongest use:** ONE line at a pivotal moment. The narrator has been doing voiceover for the entire ad, then we cut to a tight shot of a believable 50+ woman, looking directly into the camera, and she says ONE line — "You don't have to live like this." Then back to voiceover and imagery.

That one moment of direct address is more powerful than 30 seconds of talking head, and it minimizes the lip-sync challenge for the AI.

**Multiple talking-to-camera moments:** Possible, but every additional moment compounds risk. Use the same character (cohesive identity descriptions) so each appearance is more recognizable, and keep each line under 10 words.

**Avoid:** Long monologues. Multiple characters talking. Dialogue between characters (cross-shot lip sync is the absolute hardest thing for current models). Scenes where the talker is doing something complex with their hands while speaking.

**Lighting note:** Describe the talking-to-camera shots with soft, generous, slightly warm lighting. Hard light creates shadows that confuse the AI's facial generation. "Soft north light through a kitchen window, warm color palette, shallow depth of field" works.`;
}

function getNoHumansGuide(mode: FullAiSkillMode): string {
  const base = `### VISUAL STYLE — NO HUMANS SHOWN (PERSPECTIVE OF THE FEET OR SOCKS)

No humans visible. The entire ad is shot from the perspective of feet, socks, or environmental POVs. Close-ups on textures, floors, shoes, fabrics. The voiceover and on-screen text carry meaning. Scene descriptions must NEVER name a face, body, or person — only feet, legs (mid-shin down), and surrounding objects.

**Why this is powerful:** It eliminates ALL identity-consistency challenges (no faces to keep consistent, no characters to track). The AI is freed up to focus entirely on visual richness — textures, light, environment. This is often the most visually beautiful Full AI style because the model isn't fighting itself.

**The shot vocabulary is limited but rich:**
- Feet stepping (onto sand, grass, wet earth, hardwood, carpet, cobblestone)
- Feet at rest (on a footrest, against a window, in bed under a blanket)
- Feet walking (POV from behind, from below, from the side at ground level)
- Socks on/off (the moment of pulling on, the moment of relief at end of day)
- Environmental POV (the world from foot height — the kitchen floor, the garden path, the bedroom rug at sunrise)
- Anatomical visualizations (cross-section of a leg, nerves, blood vessels — see-inside views)`;

  if (mode === 'compact') return base;

  return `${base}

**This is the most avant-garde Full AI visual style — embrace it.** Don't try to make it look like a normal ad with the camera lowered. Treat the foot-perspective as a deliberate aesthetic choice and lean into it.

**Sound design becomes critical** because there are no faces or expressions to carry emotion. Every footstep on different surfaces (sand, gravel, hardwood) is part of the storytelling. Specify the sound design alongside the visual prompts.

**Voiceover note:** The VO should also avoid naming people. Use "you" or "the body" or anatomical references. "Your feet have carried you for sixty years." Not "she has walked for sixty years." This deepens the immersive POV effect.

**On-screen text:** With no faces, on-screen text becomes a co-equal storytelling tool. Use it deliberately — title cards, key facts, the offer. Treat them as visual punctuation.

**Closing:** The product reveal works exceptionally well in this style — a final beat of the sock being pulled on, or feet at rest in the socks, with the brand name appearing as title text. The lack of a human face doesn't weaken the close — it gives the viewer space to imagine themselves in the scene.`;
}

function getHistoricalVisualsGuide(mode: FullAiSkillMode): string {
  const base = `### VISUAL STYLE — HISTORICAL VISUALS AND CLAIMS

Historical visuals: period costumes, aged film grain, archival-style footage, old photographs that come to life. The CLAIMS in the ad must also be historically grounded — cite real history (origin of compression therapy, ancient foot care, WWII nurses, Roman military) to give the ad gravity and authority.

**Every voiceover claim about history must be plausibly accurate.** Don't fabricate dates, names, or discoveries. Real history gives the ad weight. Invented history collapses on the first viewer who Googles it.

**Visual treatment is rich because AI excels at period imagery:**
- Period costumes (era-specific clothing, uniforms, footwear)
- Period architecture (ancient temples, medieval workshops, Victorian parlors, WWII field hospitals)
- Period lighting (oil lamps, candles, gas lamps, early electric, golden hour through period windows)
- Aged film aesthetics (slight grain, faded colors, vignetted edges, sepia tones, slow shutter blur)
- Photographs coming to life (a still image that begins to move subtly, eyes blinking, hand reaching)
- Documents and texts (handwritten letters, ancient scrolls, medical drawings, anatomical sketches)

**This visual style pairs naturally with the Historical specification**, but it can be combined with other specifications too — e.g., a Documentary about modern circulation that uses Historical Visuals to set up the discovery sections.`;

  if (mode === 'compact') return base;

  return `${base}

**Pick a specific era and stick with it.** Don't span centuries unless the script REQUIRES it. A coherent historical world is more powerful than a montage of eras. "Late 19th century surgical theater" or "1942 field hospital" — pick one and inhabit it.

**Costume and prop specificity:** Describe costumes with period-appropriate detail. "1942 American Army nurse uniform — gray-green wool dress, white apron, white veil with a red cross, sturdy lace-up shoes." The AI will deliver if you specify.

**Aged-footage aesthetics:** Describe the film treatment alongside the visual. "Shot like 1940s newsreel footage — slight grain, slow shutter blur on movement, desaturated colors, vignetted edges, occasional film scratch." This grounds the AI in a specific visual language.

**Voiceover style:** The narration should have slight gravitas. Treat each historical claim as a piece of evidence being presented to the viewer. "In the autumn of 1943, in a field hospital outside Catania, a Red Cross nurse named..." Specific details = authority.

**Bridge to present:** When the ad transitions from historical to contemporary, mark the shift visually (the aged film treatment falls away, color saturates, the camera resolves into modern clarity). This is the moment the viewer realizes the ancient insight applies to THEIR life now.

**Critical:** Verify EVERY historical claim. If the script says "Roman soldiers wrapped their legs in linen," that should be true (it is — Roman soldiers used fasciae crurales). If it says "Hippocrates discovered compression therapy in 400 BCE," that should be defensible. When in doubt, use vaguer attribution ("Ancient physicians knew...") rather than specific fabrications.`;
}

// ─── Duration-Adapted Pacing ─────────────────────────────────────────────────

function getDurationPacing(duration: FullAiDuration, spec: FullAiSpecification, mode: FullAiSkillMode): string {
  const intro = `### DURATION-ADAPTED PACING — ${duration.toUpperCase()}`;

  if (duration === '15s') {
    return `${intro}

**This is a SUPER-SHORT Full AI ad (15 seconds).** The full 8-stage documentary arc cannot fit. Compress to the absolute essentials.

**Compressed structure (3-4 beats max):**
1. **Hook with established cause** (3-4 sec) — One sentence that names the cause/condition AND the implicit promise of a story. "Your nerves need blood. Diabetes is starving them."
2. **The insight** (4-5 sec) — One striking image or fact. "Tight socks are the final pressure they can't survive."
3. **The product as relief** (4-5 sec) — Visual of the solution, not narrated as a sales pitch. AI-rendered product moment + brand name.
4. **The CTA** (2-3 sec) — Brand + offer. "Viasox. Buy two, get three free."

**Body line count:** 3-5 lines max. Every word earns its place.

**The "establish before describe" rule still applies** — even at 15 seconds, you cannot lead with a symptom without first naming the cause. If you can't fit both, lead with the cause and skip the symptom entirely.

${spec === 'Documentary' ? '**For Documentary at 15s:** Compress stages 1, 5, 7, 8. Skip the wonder/history/science stages. The cause is the entire educational arc.' : ''}${spec === 'Historical' ? '**For Historical at 15s:** Pick ONE historical anchor and ONE present-day connection. No time for a journey through eras.' : ''}${spec === 'Educational' ? '**For Educational at 15s:** Teach ONE micro-fact, then apply it. No time for a full lesson.' : ''}${spec === 'Emotional Story' ? '**For Emotional Story at 15s:** ONE silent moment. ONE visual gesture. ONE moment of relief. No room for setup — drop the viewer directly into the moment.' : ''}${spec === 'Aspirational' ? '**For Aspirational at 15s:** Open with the vision, close with the vision realized. No time for the contrast.' : ''}

**This duration is a constraint exercise.** Don't try to do a long-form story compressed — pick ONE moment, ONE insight, ONE image, and let it carry the ad.${mode === 'full' ? '\n\nWrite the body as a 3-5 row table. NO more.' : ''}`;
  }

  if (duration === '30s') {
    return `${intro}

**This is a SHORT Full AI ad (30 seconds).** A compressed version of the documentary arc — most stages exist but each is 1-2 lines max.

**Compressed structure (5-6 beats):**
1. **Hook with established cause** (4-5 sec) — Cause-led, story-promising.
2. **The wonder OR the science** (5-6 sec) — Pick ONE. Either set up the body part as amazing, OR explain how it works. Not both.
3. **The cause + symptom** (6-8 sec) — The mechanism + the daily reality, in TWO connected lines. The "establish before describe" rule.
4. **The bridge** (5-6 sec) — Product as the natural answer.
5. **Proof + CTA** (4-5 sec) — Quick proof beat + offer.

**Body line count:** 6-9 lines.

${spec === 'Documentary' ? '**For Documentary at 30s:** Stages 2, 5, 6, 7, 8 (drop history and science as separate beats — fold them into the wonder line and the cause line).' : ''}${spec === 'Historical' ? '**For Historical at 30s:** Anchor moment (1 line), historical insight (2 lines), present-day connection (2 lines), bridge to product (2 lines), CTA (1 line).' : ''}${spec === 'Educational' ? '**For Educational at 30s:** Setup (1 line), explanation (2-3 lines), insight (1 line), application/product (2 lines), CTA (1 line).' : ''}${spec === 'Emotional Story' ? '**For Emotional Story at 30s:** Opening image (1 line), establishing detail + struggle (2-3 lines), turn + relief (2-3 lines), callback + CTA (1-2 lines).' : ''}${spec === 'Aspirational' ? '**For Aspirational at 30s:** Vision (1-2 lines), gentle contrast (1 line), promise + product (2-3 lines), new vision + CTA (2 lines).' : ''}

**Education-to-product ratio at 30s:** Roughly 60-70% educational/story / 30-40% product reveal. The shorter the ad, the higher the product proportion can be (but never above 40%).${mode === 'full' ? '\n\nWrite the body as a 6-9 row table.' : ''}`;
  }

  if (duration === '60s') {
    return `${intro}

**This is a STANDARD Full AI ad (60 seconds).** Most of the documentary arc fits, but each stage is tighter than the long-form 90s+ version.

**Structure: Compressed 8-Stage Arc.**

1. **Hook** — 4-6 sec (handled by the hook variations + optional first body line)
2. **Wonder** — 6-8 sec (1-2 body lines)
3. **History** — 6-8 sec (1-2 body lines, OR fold into wonder)
4. **Science** — 6-8 sec (1-2 body lines)
5. **Cause** — 8-10 sec (2 body lines, don't shortchange this)
6. **Problem** — 8-10 sec (2 body lines, end with "that's me" recognition)
7. **Bridge** — 8-10 sec (2-3 body lines, product as natural answer)
8. **Proof + CTA** — 6-8 sec (1-2 body lines, callback to opening)

**Body line count:** 12-16 lines.

**Education-to-product ratio at 60s:** 65-70% educational / 30-35% product reveal. The product should not appear before line 8 of a 14-line body.

${spec === 'Documentary' ? '**For Documentary at 60s:** All 8 stages exist but each is compressed. Don\'t skip stages — compress them.' : ''}${spec === 'Historical' ? '**For Historical at 60s:** Anchor era (2 lines), historical world + insight (3-4 lines), what was lost (2 lines), present connection + product (3-4 lines), CTA (1-2 lines).' : ''}${spec === 'Educational' ? '**For Educational at 60s:** Hook (1 line), lesson setup (1 line), explanation (4-5 lines), insight (1-2 lines), application + product (3-4 lines), CTA (1-2 lines).' : ''}${spec === 'Emotional Story' ? '**For Emotional Story at 60s:** Opening image (1-2 lines), establishing detail (1-2 lines), silent struggle (3-4 lines), the turn (2-3 lines), release (2-3 lines), callback + CTA (1-2 lines).' : ''}${spec === 'Aspirational' ? '**For Aspirational at 60s:** Vision (2 lines), gentle contrast (1-2 lines), promise (2 lines), why-it\'s-possible (2-3 lines), bridge to product (2-3 lines), new vision + CTA (2 lines).' : ''}${mode === 'full' ? '\n\nWrite the body as a 12-16 row table.' : ''}`;
  }

  // 90s
  return `${intro}

**This is a LONG-FORM Full AI ad (90 seconds).** This is the closest the autopilot pipeline gets to the source skill's native 2-3 minute format. The full 8-stage arc has room to breathe. This is where the format does its best work.

**Structure: Full 8-Stage Documentary Arc.**

1. **Hook** — 5-8 sec (handled by hook variations + first body line)
2. **Wonder** — 8-12 sec (2-3 body lines, sensory and rich)
3. **History** — 8-12 sec (2-3 body lines, ground in real ancient knowledge)
4. **Science** — 8-12 sec (2-3 body lines, modern explanation of healthy state)
5. **Cause** — 10-14 sec (2-3 body lines, don't shortchange — this is where the ad earns the right to discuss symptoms)
6. **Problem** — 12-16 sec (3-4 body lines, daily reality + recognition moment)
7. **Bridge** — 12-16 sec (3-4 body lines, product as natural answer)
8. **Proof + CTA** — 8-12 sec (2-3 body lines, proof + offer + emotional callback)

**Body line count:** 18-22 lines.

**Education-to-product ratio at 90s:** 65-75% educational / 25-35% product reveal. The product should not appear before line 12 of a 20-line body.

${spec === 'Documentary' ? '**For Documentary at 90s:** This is the format the skill was designed for. Use the full 8-stage arc with no compression. Each stage gets the breathing room it needs. The transition from AI-generated educational visuals to the product reveal is the signature beat — don\'t rush it.' : ''}${spec === 'Historical' ? '**For Historical at 90s:** Build an immersive historical world. Spend lines 2-8 inhabiting the era — costumes, settings, light, daily life. Earn the present-day connection with that depth.' : ''}${spec === 'Educational' ? '**For Educational at 90s:** This is room for a real lesson. Pick a single concept and teach it deeply. Use multiple AI-rendered scientific visualizations. The viewer should leave smarter even if they don\'t buy.' : ''}${spec === 'Emotional Story' ? '**For Emotional Story at 90s:** Build the world. Establish the small moment with care. Let silence carry weight. The longer runtime is your friend — DON\'T fill it with extra narration. Trust the visuals.' : ''}${spec === 'Aspirational' ? '**For Aspirational at 90s:** Build the vision in detail. Earn the transformation. The 90-second runtime is enough to take the viewer through a real arc from longing to possibility. Use the time.' : ''}

**Pacing reference (from the source skill):**
- Stage 1 (Hook): hook variations + 0-1 body line
- Stage 2 (Wonder): 2-3 body lines
- Stage 3 (History): 2-3 body lines
- Stage 4 (Science): 2-3 body lines
- Stage 5 (Cause): 2-3 body lines
- Stage 6 (Problem): 3-4 body lines
- Stage 7 (Bridge): 3-4 body lines
- Stage 8 (Proof + CTA): 2-3 body lines

Total: ~18-22 lines.

**This is the duration where the format truly shines.** Use it.${mode === 'full' ? '\n\nWrite the body as an 18-22 row table.' : ''}`;
}

// ─── Quality Bar (full mode only) ────────────────────────────────────────────

const QUALITY_BAR = `### QUALITY BAR

A good Full AI brief must pass these checks:

**1. Education/product ratio.** 65-75% of body lines are educational/story (stages 1-6). 25-35% are product reveal (stages 7-8). If the product appears too early, the ad becomes sales-y.

**2. Establishing context.** Every pain point, symptom, scary detail, or medical term is preceded by its cause earlier in the script. NO EXCEPTIONS.

**3. Tone consistency.** Documentary/story narrator throughout the educational sections. Warmer, more conversational only in the product reveal.

**4. Visual specificity.** Every "AI Generated" visual description is specific enough that a Kling/Veo/Runway prompt could be written from it directly. Avoid vague descriptions like "shot of feet" — write "macro shot of bare foot stepping onto wet earth in golden morning light, with golden nerve endings visible firing across the sole on contact, dark background, nature documentary lighting."

**5. No medical claims.** "Support," "circulation," "comfort" — yes. "Treat," "cure," "heal," "stop neuropathy" — no.

**6. AI feasibility.** Every shot can be plausibly generated by current text-to-video models. No tight branded product close-ups requiring brand-accurate detail. No multi-person dialogue with lip-sync. No complex hand-product manipulation.

**7. Cause-led hooks.** No hook leads with a symptom. Every hook establishes the cause/context before mentioning any pain point.

**8. Identity consistency.** If the visual style includes characters, the protagonist is described in obsessive first-shot detail and referenced in every subsequent shot using the same anchor.`;

const AUDIT_CHECKLIST = `### FINAL AUDIT CHECKLIST

Before finalizing the script, sweep the entire body and check every line that mentions:

- A symptom (tingling, numbness, burning, pain, swelling, fatigue, aching)
- A visible problem (sock marks, dents, redness, swelling, discoloration)
- A medical condition (neuropathy, diabetes, edema, plantar fasciitis, etc.)
- A scary detail (nerves dying, blood being cut off, ulcers, wounds)
- A demographic claim ("30 million Americans," "millions of people")

For each one, find the line earlier in the script that establishes WHY this matters for the target customer. If no such line exists:

1. **Insert an establishing line earlier** — usually a single sentence naming the cause/condition and how it works
2. **Move the line later in the script**, after the cause is established
3. **If neither fix works, cut the line entirely**

This is the single most common quality issue and the easiest to overlook. Do the audit. Don't skip it.`;
